type glbs = {
  [key: string]: string;
};

export const glbs: glbs = {
  // bird~house까지 다 이미지 루트 고쳐야 함
  man_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Man1.glb',
  login_earth_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/loginEarth.glb',
  house_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_1.glb',
  house_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_2.glb',
  house_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_3.glb',
  house_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_4.glb',
  house_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_5.glb',
  tree_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree1.glb',
  tree_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree2.glb',
  tree_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree3.glb',
  tree_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree4.glb',
  tree_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree5.glb',
  tree_6_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree6.glb',
  tree_7_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree7.glb',
  tree_8_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree8.glb',
  tree_9_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree9.glb',
  branch_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Branch.glb',
  seed_glb: 'https://storage.googleapis.com/churest-bucket/project_3D/Seed.glb',
  sprout_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Sprout.glb',
  char_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char1.glb',
  char_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char2.glb',
  char_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char3.glb',
  char_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char4.glb',
  char_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char5.glb',
  char_6_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char6.glb',
  post_box_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/PostBox.glb',
  birdhouse_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/BirdHouse1.glb',
  birdhouse_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/BirdHouse2.glb',
  birdhouse_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/BirdHouse3.glb',
  plant_ok_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/PlantOk.glb',
  plant_no_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/PlantNo.glb',
  churest_map_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/ChurestMap.glb',
  error_404_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Error404.glb', 
};
