type glbs = {
  [key: string]: string;
};

export const glbs: glbs = {
  man_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Man1.glb',
  login_earth_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/loginEarth.glb',
  house_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_1.glb',
  house_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_2.glb',
  house_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_3.glb',
  house_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/home_4.glb',
  house_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/home_5.glb',
  house_6_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/house_7.glb',
  tree_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree1.glb',
  tree_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree2.glb',
  tree_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree3.glb',
  tree_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree4.glb',
  tree_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree5.glb',
  tree_6_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree6.glb',
  tree_7_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree7.glb',
  tree_8_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree8.glb',
  tree_9_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Tree9.glb',
  branch_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Branch.glb',
  seed_glb: 'https://storage.googleapis.com/churest-bucket/project_3D/Seed.glb',
  sprout_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/SproutSand.glb',
  char_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char1.glb',
  char_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char2.glb',
  char_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char3.glb',
  char_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char4.glb',
  char_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char5.glb',
  char_6_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Char6.glb',
  post_box_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/PostBox.glb',
  birdhouse_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/BirdHouse1.glb',
  birdhouse_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/BirdHouse2.glb',
  birdhouse_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/BirdHouse3.glb',
  plant_ok_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/PlantOk.glb',
  plant_no_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/PlantNo.glb',
  churest_map_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/ChurestMapLast.glb',
  mountain_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Mountain.glb',
  rock_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Rock1.glb',
  rock_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Rock2.glb',
  rock_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Rock3.glb',
  rock_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Rock4.glb',
  rock_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Rock5.glb',
  error_404_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Error404.glb',
  bird_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/bird1.glb',
  bird_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/bird2.glb',
  bird_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/bird3.glb',
  bird_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/bird4.glb',
  bird_5_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/bird5.glb',
  bird_6_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/bird6.glb',
  bird_7_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/bird7.glb',
  churest_map_11_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/ChurestMap11x11.glb',
  tile_glb: 'https://storage.googleapis.com/churest-bucket/project_3D/tile.glb',
  square_map_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/SquareMap.glb',
  g_map_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_map.glb',
  g_map_floor_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_mapFloor.glb',
  g_liver_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_liver.glb',
  g_bridge_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_bridge.glb',
  g_animal_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_animal1.glb',
  g_animal_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_animal2.glb',
  g_animal_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_animal3.glb',
  g_animal_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_animal4.glb',
  g_around_bridge_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_around_bridge.glb',
  g_arrows_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_arrows.glb',
  g_big_tree_around_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_big_tree_around.glb',
  g_big_tree_bottom_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_big_tree_bottom.glb',
  g_boxes_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_boxes.glb',
  g_branches_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_branches.glb',
  g_buildingFirst_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_buildingFirst.glb',
  g_buildingGreen_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_buildingGreen.glb',
  g_buildingSecond_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_buildingSecond.glb',
  g_flower_blue_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_flowerBlue.glb',
  g_flower_red_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_flowerRed.glb',
  g_market_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_market.glb',
  g_mushroom_left_top_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_mushroom_left_top.glb',
  g_oaktong_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_oaktong.glb',
  g_rocks_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_rocks.glb',
  g_stones_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_stones.glb',
  g_table_chair_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_tableChair.glb',
  g_woomul_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_woomul.glb',
  g_tree_bottom_right_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_tree_right_bottom.glb',
  g_tree_bottom_left_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_tree_left_bottom.glb',
  g_tree_right_top_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_tree_right_top.glb',
  g_big_tree_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_big_tree.glb',
  g_world_tree_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/g_worldTree.glb',
  flower_red_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Flower_Red.glb',
  flower_white_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Flower_White.glb',
  flower_blue_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Flower_Blue_Small.glb',
  flower_pink_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Flower_Pink.glb',
  t_flower_1_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/tFlower_1.glb',
  t_flower_2_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/tFlower_2.glb',
  t_flower_3_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/tFlower_3.glb',
  t_flower_4_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/tFlower_4.glb',
  flower_grass_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Flower_Grass.glb',
  flower_orange_glb:
    'https://storage.googleapis.com/churest-bucket/project_3D/Flower_Orange_Small.glb',
};
