type Images = {
  [key: string]: string;
};

export const images: Images = {
  // bird~house까지 다 이미지 루트 고쳐야 함
  bird_1_img:
    'https://storage.googleapis.com/churest-bucket/project_image/bird_1_img.png',
  bird_2_img:
    'https://storage.googleapis.com/churest-bucket/project_image/bird_2_img.png',
  bird_3_img:
    'https://storage.googleapis.com/churest-bucket/project_image/bird_3_img.png',
  bird_4_img:
    'https://storage.googleapis.com/churest-bucket/project_image/bird_4_img.png',
  bird_5_img:
    'https://storage.googleapis.com/churest-bucket/project_image/bird_5_img.png',
  bird_6_img:
    'https://storage.googleapis.com/churest-bucket/project_image/bird_6_img.png',
  bird_7_img:
    'https://storage.googleapis.com/churest-bucket/project_image/bird_7_img.png',
  house_1_img:
    'https://storage.googleapis.com/churest-bucket/project_image/house_1_img.png',
  house_2_img:
    'https://storage.googleapis.com/churest-bucket/project_image/house_2_img.png',
  house_3_img:
    'https://storage.googleapis.com/churest-bucket/project_image/house_3_img.png',
  house_4_img:
    'https://storage.googleapis.com/churest-bucket/project_image/house_4_img.png',
  house_5_img:
    'https://storage.googleapis.com/churest-bucket/project_image/house_5_img.png',
  house_6_img:
    'https://storage.googleapis.com/churest-bucket/project_image/house_6_img.png',
  avatar_1_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Char_1.png',
  avatar_2_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Char_2.png',
  avatar_3_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Char_3.png',
  avatar_4_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Char_4.png',
  avatar_5_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Char_5.png',
  avatar_6_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Char_6.png',
  nest_1_img:
    'https://storage.googleapis.com/churest-bucket/project_image/nest_1_img.png',
  nest_2_img:
    'https://storage.googleapis.com/churest-bucket/project_image/nest_2_img.png',
  nest_3_img:
    'https://storage.googleapis.com/churest-bucket/project_image/nest_3_img.png',
  letter_img:
    'https://storage.googleapis.com/churest-bucket/project_image/letter_img.png',
  my_tree_img:
    'https://storage.googleapis.com/churest-bucket/project_image/my_tree_img.png',
  chuworld_img:
    'https://storage.googleapis.com/churest-bucket/project_image/chuworld_img.png',
  cloud_img:
    'https://storage.googleapis.com/churest-bucket/project_image/cloud_img.png',
  chuworld_bubble_img:
    'https://storage.googleapis.com/churest-bucket/project_image/chuworld_bubble_img.png',
  alarm_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/alarm_navbar_img.png',
  churest_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/churest_navbar_img.png',
  garden_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/garden_navbar_img.png',
  mypage_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/mypage_navbar_img.png',
  search_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/search_navbar_img.png',
  tag_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/tag_navbar_img.png',
  chuworld_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/chuworld_navbar_img.png',
  cloudy_img:
    'https://storage.googleapis.com/churest-bucket/project_image/cloudy_img.png',
  thunder_img:
    'https://storage.googleapis.com/churest-bucket/project_image/thunder_img.png',
  snowy_img:
    'https://storage.googleapis.com/churest-bucket/project_image/snowy_img.png',
  rainy_img:
    'https://storage.googleapis.com/churest-bucket/project_image/rainy_img.png',
  foggy_img:
    'https://storage.googleapis.com/churest-bucket/project_image/foggy_img.png',
  sunny_img:
    'https://storage.googleapis.com/churest-bucket/project_image/sunny_img.png',
  memory_img:
    'https://storage.googleapis.com/churest-bucket/project_image/memory_img.png',
  shop_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/shop_navbar_img.png',
  coin_navbar_img:
    'https://storage.googleapis.com/churest-bucket/project_image/coin_navbar_img.png',
  chuworld2_img:
    'https://storage.googleapis.com/churest-bucket/project_image/chuworld2_img.png',
  watering_icon_img:
    'https://storage.googleapis.com/churest-bucket/project_image/watering_icon_img.png',
  tree_1_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree1.png',
  tree_2_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree2.png',
  tree_3_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree3.png',
  tree_4_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree4.png',
  tree_5_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree5.png',
  tree_6_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree6.png',
  tree_7_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree7.png',
  tree_8_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree8.png',
  tree_9_img:
    'https://storage.googleapis.com/churest-bucket/project_image/Tree9.png',
  save_plant_img:
    'https://storage.googleapis.com/churest-bucket/project_image/save_plant.png',
  save_earth_img:
    'https://storage.googleapis.com/churest-bucket/project_image/save_earth.png',
};
