/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bird7.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube003_2: THREE.Mesh;
    Cube003_3: THREE.Mesh;
    Cube003_4: THREE.Mesh;
    Cube003_5: THREE.Mesh;
    Cube003_6: THREE.Mesh;
    Cube003_7: THREE.Mesh;
  };
  materials: {
    ['매테리얼.001']: THREE.MeshStandardMaterial;
    매테리얼: THREE.MeshStandardMaterial;
    ['Material.047']: THREE.MeshStandardMaterial;
    ['Material.048']: THREE.MeshStandardMaterial;
    ['Material.049']: THREE.MeshStandardMaterial;
    ['Material.050']: THREE.MeshStandardMaterial;
    ['Material.051']: THREE.MeshStandardMaterial;
    ['Material.052']: THREE.MeshStandardMaterial;
  };
};

export function Bird7(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.bird_7_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.11, -0.13, 0.09]}
        rotation={[-0.05, 0.24, 0.2]}
        scale={0.42}
      >
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials['매테리얼.001']}
          castShadow
        />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials.매테리얼}
          castShadow
        />
        <mesh
          geometry={nodes.Cube003_2.geometry}
          material={materials['Material.047']}
          castShadow
        />
        <mesh
          geometry={nodes.Cube003_3.geometry}
          material={materials['Material.048']}
          castShadow
        />
        <mesh
          geometry={nodes.Cube003_4.geometry}
          material={materials['Material.049']}
          castShadow
        />
        <mesh
          geometry={nodes.Cube003_5.geometry}
          material={materials['Material.050']}
          castShadow
        />
        <mesh
          geometry={nodes.Cube003_6.geometry}
          material={materials['Material.051']}
          castShadow
        />
        <mesh
          geometry={nodes.Cube003_7.geometry}
          material={materials['Material.052']}
          castShadow
        />
      </group>
    </group>
  );
}

// useGLTF.preload(glbs.bird_7_glb);
