/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bird6.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    Cube002_3: THREE.Mesh;
    Cube002_4: THREE.Mesh;
    Cube002_5: THREE.Mesh;
  };
  materials: {
    ['Material.041']: THREE.MeshStandardMaterial;
    ['Material.042']: THREE.MeshStandardMaterial;
    ['Material.043']: THREE.MeshStandardMaterial;
    ['Material.044']: THREE.MeshStandardMaterial;
    ['Material.045']: THREE.MeshStandardMaterial;
    ['Material.046']: THREE.MeshStandardMaterial;
  };
};

export function Bird6(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.bird_6_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.66, 1.23, 0.03]} rotation={[0, 0, 0.13]} scale={0.54}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials['Material.041']}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials['Material.042']}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials['Material.043']}
        />
        <mesh
          geometry={nodes.Cube002_3.geometry}
          material={materials['Material.044']}
        />
        <mesh
          geometry={nodes.Cube002_4.geometry}
          material={materials['Material.045']}
        />
        <mesh
          geometry={nodes.Cube002_5.geometry}
          material={materials['Material.046']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.bird_6_glb);
