/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 bird5.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Sphere002: THREE.Mesh;
    Sphere002_1: THREE.Mesh;
    Sphere002_2: THREE.Mesh;
    Sphere002_3: THREE.Mesh;
    Sphere002_4: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
  };
};

export function Bird5(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.bird_5_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.24, 1.28, 0.71]} scale={0.05}>
        <mesh
          geometry={nodes.Sphere002.geometry}
          material={materials['Material.001']}
          castShadow
        />
        <mesh
          geometry={nodes.Sphere002_1.geometry}
          material={materials['Material.002']}
          castShadow
        />
        <mesh
          geometry={nodes.Sphere002_2.geometry}
          material={materials['Material.004']}
          castShadow
        />
        <mesh
          geometry={nodes.Sphere002_3.geometry}
          material={materials['Material.005']}
          castShadow
        />
        <mesh
          geometry={nodes.Sphere002_4.geometry}
          material={materials['Material.007']}
          castShadow
        />
      </group>
    </group>
  );
}

// useGLTF.preload(glbs.bird_5_glb);
