/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 house_4.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    building005: THREE.Mesh;
  };
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial;
  };
};

export function House4(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.house_4_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.building005.geometry}
        material={materials['Material.004']}
        position={[0, 2.1, 0]}
        scale={[0.56, 0.44, 0.56]}
      />
    </group>
  );
}

useGLTF.preload(glbs.house_4_glb);
