/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_animal2.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    animal2: THREE.Mesh;
  };
  materials: {
    ['Material.090']: THREE.MeshStandardMaterial;
  };
};

export function G_animal2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_animal_2_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.animal2.geometry}
        material={materials['Material.090']}
        position={[-7.46, 2.38, -7.8]}
        rotation={[-Math.PI, 1.43, -Math.PI]}
        scale={0.85}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_animal_2_glb);
