/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_around_bridge.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Mesh094: THREE.Mesh;
    Mesh094_1: THREE.Mesh;
  };
  materials: {
    ['Material.092']: THREE.MeshStandardMaterial;
    ['Material.093']: THREE.MeshStandardMaterial;
  };
};

export function G_around_bridge(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_around_bridge_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-16.31, 0.6, -7.69]}
        rotation={[0.22, 0, 0]}
        scale={0.24}
      >
        <mesh
          geometry={nodes.Mesh094.geometry}
          material={materials['Material.092']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh094_1.geometry}
          material={materials['Material.093']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.g_around_bridge_glb);
