/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_arrows.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Mesh519: THREE.Mesh;
    Mesh519_1: THREE.Mesh;
  };
  materials: {
    ['Material.070']: THREE.MeshStandardMaterial;
    ['Material.073']: THREE.MeshStandardMaterial;
  };
};

export function G_arrows(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_arrows_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.82, 1.46, 4.97]}
        rotation={[0, -0.84, 0]}
        scale={0.57}
      >
        <mesh
          geometry={nodes.Mesh519.geometry}
          material={materials['Material.070']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh519_1.geometry}
          material={materials['Material.073']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.g_arrows_glb);
