/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_big_tree.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    메쉬059: THREE.Mesh;
    메쉬059_1: THREE.Mesh;
    메쉬059_2: THREE.Mesh;
    메쉬059_3: THREE.Mesh;
    메쉬059_4: THREE.Mesh;
    메쉬059_5: THREE.Mesh;
    메쉬059_6: THREE.Mesh;
    메쉬059_7: THREE.Mesh;
    메쉬059_8: THREE.Mesh;
    메쉬059_9: THREE.Mesh;
    메쉬059_10: THREE.Mesh;
  };
  materials: {
    ['매테리얼.023']: THREE.MeshStandardMaterial;
    ['매테리얼.024']: THREE.MeshStandardMaterial;
    ['매테리얼.025']: THREE.MeshStandardMaterial;
    ['매테리얼.030']: THREE.MeshStandardMaterial;
    ['매테리얼.031']: THREE.MeshStandardMaterial;
    ['매테리얼.032']: THREE.MeshStandardMaterial;
    ['매테리얼.033']: THREE.MeshStandardMaterial;
    ['매테리얼.034']: THREE.MeshStandardMaterial;
    ['매테리얼.035']: THREE.MeshStandardMaterial;
    ['매테리얼.036']: THREE.MeshStandardMaterial;
    ['매테리얼.037']: THREE.MeshStandardMaterial;
  };
};

export function G_big_tree(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_big_tree_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.05, 8.33, -11.16]}
        rotation={[-0.06, -0.33, 0.28]}
        scale={[0.71, 0.45, 1.2]}
      >
        <mesh
          geometry={nodes.메쉬059.geometry}
          material={materials['매테리얼.023']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_1.geometry}
          material={materials['매테리얼.024']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_2.geometry}
          material={materials['매테리얼.025']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_3.geometry}
          material={materials['매테리얼.030']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_4.geometry}
          material={materials['매테리얼.031']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_5.geometry}
          material={materials['매테리얼.032']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_6.geometry}
          material={materials['매테리얼.033']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_7.geometry}
          material={materials['매테리얼.034']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_8.geometry}
          material={materials['매테리얼.035']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_9.geometry}
          material={materials['매테리얼.036']}
          castShadow
        />
        <mesh
          geometry={nodes.메쉬059_10.geometry}
          material={materials['매테리얼.037']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.g_big_tree_glb);
