/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_buildingFirst.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    buildingFirst: THREE.Mesh;
  };
  materials: {
    ['Material.007']: THREE.MeshStandardMaterial;
  };
};

export function G_buildingFirst(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_buildingFirst_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.buildingFirst.geometry}
        material={materials['Material.007']}
        position={[9.94, 1.3, 14.82]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.63}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_buildingFirst_glb);
