/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_buildingSecond.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    buildingSecond: THREE.Mesh;
  };
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial;
  };
};

export function G_buildingSecond(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_buildingSecond_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.buildingSecond.geometry}
        material={materials['Material.006']}
        position={[10.98, 2.37, 7.68]}
        rotation={[0, -1.57, 0]}
        scale={0.61}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_buildingSecond_glb);
