/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_flowerBlue.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    flowerBlue: THREE.Mesh;
  };
  materials: {
    ['Material.067']: THREE.MeshStandardMaterial;
  };
};

export function G_flower_blue(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_flower_blue_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.flowerBlue.geometry}
        material={materials['Material.067']}
        position={[4.21, 0.3, 16.19]}
        rotation={[0, 0.92, 0]}
        scale={0.17}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_flower_blue_glb);
