/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_flowerRed.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    flowerRed: THREE.Mesh;
  };
  materials: {
    ['Material.065']: THREE.MeshStandardMaterial;
  };
};

export function G_flower_red(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_flower_red_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.flowerRed.geometry}
        material={materials['Material.065']}
        position={[-5.67, 0.43, 6.33]}
        rotation={[0, 1.07, 0]}
        scale={0.16}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_flower_red_glb);
