/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_liver.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    liver: THREE.Mesh;
  };
  materials: {
    매테리얼: THREE.MeshStandardMaterial;
  };
};

export function G_liver(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_liver_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.liver.geometry}
        material={materials.매테리얼}
        position={[0, -6.39, 0]}
        rotation={[0, -1.57, 0]}
        scale={[18, 2, 18]}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_liver_glb);
