/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_mushroom_left_top.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Mesh033: THREE.Mesh;
    Mesh033_1: THREE.Mesh;
    Mesh033_2: THREE.Mesh;
    Mesh033_3: THREE.Mesh;
    Mesh033_4: THREE.Mesh;
    Mesh033_5: THREE.Mesh;
  };
  materials: {
    ['Material.022']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
    ['Material.011']: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
    ['Material.014']: THREE.MeshStandardMaterial;
    ['Material.015']: THREE.MeshStandardMaterial;
  };
};

export function G_mushroom_left_top(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    glbs.g_mushroom_left_top_glb
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-11.01, 1.07, -15.47]}
        rotation={[2.96, -0.96, 2.97]}
        scale={0.04}
      >
        <mesh
          geometry={nodes.Mesh033.geometry}
          material={materials['Material.022']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh033_1.geometry}
          material={materials['Material.010']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh033_2.geometry}
          material={materials['Material.011']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh033_3.geometry}
          material={materials['Material.013']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh033_4.geometry}
          material={materials['Material.014']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh033_5.geometry}
          material={materials['Material.015']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.g_mushroom_left_top_glb);
