/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_oaktong.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Mesh498: THREE.Mesh;
    Mesh498_1: THREE.Mesh;
  };
  materials: {
    ['Material.016']: THREE.MeshStandardMaterial;
    ['Material.017']: THREE.MeshStandardMaterial;
  };
};

export function G_oaktong(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_oaktong_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[14.28, 0.39, 7.22]}
        rotation={[0, 1.57, 0]}
        scale={0.34}
      >
        <mesh
          geometry={nodes.Mesh498.geometry}
          material={materials['Material.016']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh498_1.geometry}
          material={materials['Material.017']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.g_oaktong_glb);
