/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_rocks.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Mesh471: THREE.Mesh;
    Mesh471_1: THREE.Mesh;
  };
  materials: {
    ['Material.030']: THREE.MeshStandardMaterial;
    ['Material.036']: THREE.MeshStandardMaterial;
  };
};

export function G_rocks(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_rocks_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[3.09, 0.64, 5.48]} scale={0.22}>
        <mesh
          geometry={nodes.Mesh471.geometry}
          material={materials['Material.030']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh471_1.geometry}
          material={materials['Material.036']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.g_rocks_glb);
