/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_tableChair.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Mesh518: THREE.Mesh;
    Mesh518_1: THREE.Mesh;
  };
  materials: {
    ['Material.069']: THREE.MeshStandardMaterial;
    ['Material.068']: THREE.MeshStandardMaterial;
  };
};

export function G_table_chair(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_table_chair_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[4.4, 0.5, 12.72]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.57}
      >
        <mesh
          geometry={nodes.Mesh518.geometry}
          material={materials['Material.069']}
          castShadow
        />
        <mesh
          geometry={nodes.Mesh518_1.geometry}
          material={materials['Material.068']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.g_table_chair_glb);
