/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_tree_left_bottom.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    fantasy_plant041: THREE.Mesh;
    fantasy_plant042: THREE.Mesh;
    fantasy_plant043: THREE.Mesh;
    fantasy_plant044: THREE.Mesh;
    fantasy_plant045: THREE.Mesh;
    fantasy_plant046: THREE.Mesh;
    fantasy_plant047: THREE.Mesh;
    fantasy_plant024: THREE.Mesh;
    fantasy_plant025: THREE.Mesh;
    fantasy_plant026: THREE.Mesh;
    fantasy_plant027: THREE.Mesh;
    fantasy_plant028: THREE.Mesh;
    fantasy_plant029: THREE.Mesh;
    fantasy_plant030: THREE.Mesh;
    fantasy_plant031: THREE.Mesh;
    fantasy_plant032: THREE.Mesh;
    fantasy_plant033: THREE.Mesh;
    fantasy_plant035: THREE.Mesh;
    fantasy_plant036: THREE.Mesh;
    fantasy_plant038: THREE.Mesh;
    fantasy_plant039: THREE.Mesh;
    fantasy_plant040: THREE.Mesh;
    fantasy_plant163: THREE.Mesh;
    fantasy_plant168: THREE.Mesh;
  };
  materials: {
    ['Material.032']: THREE.MeshStandardMaterial;
    ['Material.033']: THREE.MeshStandardMaterial;
    ['매테리얼.006']: THREE.MeshStandardMaterial;
    ['Material.024']: THREE.MeshStandardMaterial;
    ['매테리얼.007']: THREE.MeshStandardMaterial;
    ['Material.027']: THREE.MeshStandardMaterial;
  };
};

export function G_tree_left_bottom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    glbs.g_tree_bottom_left_glb
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.fantasy_plant041.geometry}
        material={materials['Material.032']}
        position={[-17.08, 1.69, 16.83]}
        scale={0.5}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant042.geometry}
        material={materials['Material.032']}
        position={[-17.08, 1.69, 12.27]}
        scale={0.5}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant043.geometry}
        material={materials['Material.032']}
        position={[-17.08, 1.69, 8.27]}
        scale={0.5}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant044.geometry}
        material={materials['Material.032']}
        position={[-17.08, 1.69, 3.99]}
        scale={0.5}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant045.geometry}
        material={materials['Material.033']}
        position={[-14.45, 1.65, 5.84]}
        scale={0.52}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant046.geometry}
        material={materials['Material.033']}
        position={[-14.45, 1.65, 10.43]}
        scale={0.52}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant047.geometry}
        material={materials['Material.033']}
        position={[-14.45, 1.65, 14.04]}
        scale={0.52}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant024.geometry}
        material={materials['매테리얼.006']}
        position={[-14.42, 1.55, 16.15]}
        rotation={[0, -0.58, 0]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant025.geometry}
        material={materials['Material.024']}
        position={[-14.42, 1.55, 12.15]}
        rotation={[Math.PI, -0.79, Math.PI]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant026.geometry}
        material={materials['매테리얼.006']}
        position={[-14.42, 1.55, 12.15]}
        rotation={[Math.PI, -0.79, Math.PI]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant027.geometry}
        material={materials['Material.024']}
        position={[-14.42, 1.55, 8.15]}
        rotation={[0, -0.11, 0]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant028.geometry}
        material={materials['매테리얼.006']}
        position={[-14.42, 1.55, 8.15]}
        rotation={[0, -0.11, 0]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant029.geometry}
        material={materials['Material.024']}
        position={[-14.42, 1.55, 4.15]}
        rotation={[0, 0.85, 0]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant030.geometry}
        material={materials['매테리얼.006']}
        position={[-14.42, 1.55, 4.15]}
        rotation={[0, 0.85, 0]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant031.geometry}
        material={materials['매테리얼.007']}
        position={[-17.17, 1.56, 6.27]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant032.geometry}
        material={materials['매테리얼.007']}
        position={[-17.17, 1.56, 6.27]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant033.geometry}
        material={materials['Material.027']}
        position={[-17.17, 1.56, 10.27]}
        rotation={[-Math.PI, 1.14, -Math.PI]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant035.geometry}
        material={materials['매테리얼.007']}
        position={[-17.17, 1.56, 10.27]}
        rotation={[-Math.PI, 1.14, -Math.PI]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant036.geometry}
        material={materials['매테리얼.007']}
        position={[-17.17, 1.56, 10.27]}
        rotation={[-Math.PI, 1.14, -Math.PI]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant038.geometry}
        material={materials['Material.027']}
        position={[-17.17, 1.56, 14.27]}
        rotation={[0, 0.96, 0]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant039.geometry}
        material={materials['매테리얼.007']}
        position={[-17.17, 1.56, 14.27]}
        rotation={[0, 0.96, 0]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant040.geometry}
        material={materials['매테리얼.007']}
        position={[-17.17, 1.56, 14.27]}
        rotation={[0, 0.96, 0]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant163.geometry}
        material={materials['Material.024']}
        position={[-14.42, 1.55, 16.15]}
        rotation={[0, -0.58, 0]}
        scale={0.11}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant168.geometry}
        material={materials['Material.027']}
        position={[-17.17, 1.56, 6.27]}
        scale={0.1}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_tree_bottom_left_glb);
