/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_tree_right_bottom.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    fantasy_plant034: THREE.Mesh;
    fantasy_plant037: THREE.Mesh;
    fantasy_plant113: THREE.Mesh;
    fantasy_plant001: THREE.Mesh;
    fantasy_plant002: THREE.Mesh;
    fantasy_plant003: THREE.Mesh;
    fantasy_plant004: THREE.Mesh;
    fantasy_plant005: THREE.Mesh;
    fantasy_plant006: THREE.Mesh;
    fantasy_plant007: THREE.Mesh;
    fantasy_plant008: THREE.Mesh;
    fantasy_plant009: THREE.Mesh;
    fantasy_plant010: THREE.Mesh;
    fantasy_plant011: THREE.Mesh;
    fantasy_plant012: THREE.Mesh;
    fantasy_plant013: THREE.Mesh;
    fantasy_plant014: THREE.Mesh;
    fantasy_plant015: THREE.Mesh;
    fantasy_plant016: THREE.Mesh;
    fantasy_plant017: THREE.Mesh;
    fantasy_plant018: THREE.Mesh;
    fantasy_plant019: THREE.Mesh;
    fantasy_plant020: THREE.Mesh;
    fantasy_plant021: THREE.Mesh;
    fantasy_plant022: THREE.Mesh;
    fantasy_plant023: THREE.Mesh;
  };
  materials: {
    ['Material.064']: THREE.MeshStandardMaterial;
    ['Material.087']: THREE.MeshStandardMaterial;
    ['Material.020']: THREE.MeshStandardMaterial;
    ['매테리얼.005']: THREE.MeshStandardMaterial;
    ['매테리얼.004']: THREE.MeshStandardMaterial;
  };
};

export function G_tree_right_bottom(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    glbs.g_tree_bottom_right_glb
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.fantasy_plant113.geometry}
        material={materials['Material.020']}
        position={[16.43, 2.48, 16.78]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant001.geometry}
        material={materials['매테리얼.005']}
        position={[16.43, 2.48, 16.78]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant002.geometry}
        material={materials['매테리얼.004']}
        position={[16.43, 2.48, 16.78]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant003.geometry}
        material={materials['매테리얼.004']}
        position={[16.43, 2.48, 16.78]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant004.geometry}
        material={materials['Material.020']}
        position={[16, 2.83, 13.54]}
        rotation={[0, -1.27, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant005.geometry}
        material={materials['매테리얼.005']}
        position={[16, 2.83, 13.54]}
        rotation={[0, -1.27, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant006.geometry}
        material={materials['매테리얼.004']}
        position={[16, 2.83, 13.54]}
        rotation={[0, -1.27, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant007.geometry}
        material={materials['매테리얼.004']}
        position={[16, 2.83, 13.54]}
        rotation={[0, -1.27, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant008.geometry}
        material={materials['Material.020']}
        position={[16, 2.35, 10.73]}
        rotation={[0, -0.51, 0]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant009.geometry}
        material={materials['매테리얼.005']}
        position={[16, 2.35, 10.73]}
        rotation={[0, -0.51, 0]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant010.geometry}
        material={materials['매테리얼.004']}
        position={[16, 2.35, 10.73]}
        rotation={[0, -0.51, 0]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant011.geometry}
        material={materials['매테리얼.004']}
        position={[16, 2.35, 10.73]}
        rotation={[0, -0.51, 0]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant012.geometry}
        material={materials['Material.020']}
        position={[16.88, 3.07, 7.76]}
        rotation={[0, -1.06, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant013.geometry}
        material={materials['매테리얼.005']}
        position={[16.88, 3.07, 7.76]}
        rotation={[0, -1.06, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant014.geometry}
        material={materials['매테리얼.004']}
        position={[16.88, 3.07, 7.76]}
        rotation={[0, -1.06, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant015.geometry}
        material={materials['매테리얼.004']}
        position={[16.88, 3.07, 7.76]}
        rotation={[0, -1.06, 0]}
        scale={0.12}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant016.geometry}
        material={materials['Material.020']}
        position={[15.94, 3.07, 4.71]}
        rotation={[0, -1.06, 0]}
        scale={0.14}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant017.geometry}
        material={materials['매테리얼.005']}
        position={[15.94, 3.07, 4.71]}
        rotation={[0, -1.06, 0]}
        scale={0.14}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant018.geometry}
        material={materials['매테리얼.004']}
        position={[15.94, 3.07, 4.71]}
        rotation={[0, -1.06, 0]}
        scale={0.14}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant019.geometry}
        material={materials['매테리얼.004']}
        position={[15.94, 3.07, 4.71]}
        rotation={[0, -1.06, 0]}
        scale={0.14}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant020.geometry}
        material={materials['Material.020']}
        position={[15.94, 2.4, 2.36]}
        rotation={[Math.PI, -1.37, Math.PI]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant021.geometry}
        material={materials['매테리얼.005']}
        position={[15.94, 2.4, 2.36]}
        rotation={[Math.PI, -1.37, Math.PI]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant022.geometry}
        material={materials['매테리얼.004']}
        position={[15.94, 2.4, 2.36]}
        rotation={[Math.PI, -1.37, Math.PI]}
        scale={0.1}
        castShadow
      />
      <mesh
        geometry={nodes.fantasy_plant023.geometry}
        material={materials['매테리얼.004']}
        position={[15.94, 2.4, 2.36]}
        rotation={[Math.PI, -1.37, Math.PI]}
        scale={0.1}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_tree_bottom_right_glb);
