/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 g_woomul.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    WooMul: THREE.Mesh;
  };
  materials: {
    ['Material.072']: THREE.MeshStandardMaterial;
  };
};

export function G_woomul(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.g_woomul_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.WooMul.geometry}
        material={materials['Material.072']}
        position={[-2.44, 0.49, 12.92]}
        rotation={[0, -1.57, 0]}
        scale={0.39}
        castShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.g_woomul_glb);
