/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ChurestMap11.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    큐브_1: THREE.Mesh;
    큐브_2: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    매테리얼: THREE.MeshStandardMaterial;
  };
};

export function ChurestMap11(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.churest_map_11_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={[22, 1, 22]}>
        <mesh
          geometry={nodes.큐브_1.geometry}
          material={materials.Material}
          receiveShadow
        />
        <mesh
          geometry={nodes.큐브_2.geometry}
          material={materials.매테리얼}
          receiveShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.churest_map_11_glb);
