/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ChurestMapLast.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    큐브001_1: THREE.Mesh;
    큐브001_2: THREE.Mesh;
    큐브001_3: THREE.Mesh;
    큐브002: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
    매테리얼: THREE.MeshStandardMaterial;
    ['매테리얼.002']: THREE.MeshStandardMaterial;
    ['매테리얼.001']: THREE.MeshStandardMaterial;
  };
};

export function ChurestMap(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.churest_map_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1, 0]} scale={[22, 1, 22]}>
        <mesh
          geometry={nodes.큐브001_1.geometry}
          material={materials['Material.001']}
          receiveShadow
        />
        <mesh
          geometry={nodes.큐브001_2.geometry}
          material={materials.매테리얼}
          receiveShadow
        />
        <mesh
          geometry={nodes.큐브001_3.geometry}
          material={materials['매테리얼.002']}
        />
      </group>
      <mesh
        geometry={nodes.큐브002.geometry}
        material={materials['매테리얼.001']}
        position={[0, -3, 0]}
        scale={[22, 1, 22]}
      />
    </group>
  );
}

useGLTF.preload(glbs.churest_map_glb);
