/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Error404.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    아이코스피어_1: THREE.Mesh;
    아이코스피어_2: THREE.Mesh;
    아이코스피어_3: THREE.Mesh;
    아이코스피어001: THREE.Mesh;
    tree: THREE.Mesh;
    tree001: THREE.Mesh;
    tree002: THREE.Mesh;
    tree003: THREE.Mesh;
    tree004: THREE.Mesh;
    tree005: THREE.Mesh;
    tree006: THREE.Mesh;
    tree007: THREE.Mesh;
    tree008: THREE.Mesh;
    tree009: THREE.Mesh;
    tree010: THREE.Mesh;
    tree011: THREE.Mesh;
    tree012: THREE.Mesh;
    tree013: THREE.Mesh;
    tree014: THREE.Mesh;
    tree015: THREE.Mesh;
    tree016: THREE.Mesh;
    tree017: THREE.Mesh;
    tree018: THREE.Mesh;
    tree019: THREE.Mesh;
    tree020: THREE.Mesh;
    tree021: THREE.Mesh;
    tree022: THREE.Mesh;
    tree023: THREE.Mesh;
    tree024: THREE.Mesh;
    tree025: THREE.Mesh;
    tree026: THREE.Mesh;
    tree027: THREE.Mesh;
    tree028: THREE.Mesh;
    tree029: THREE.Mesh;
    tree030: THREE.Mesh;
    tree031: THREE.Mesh;
    평면001_1: THREE.Mesh;
    평면001_2: THREE.Mesh;
    평면005_1: THREE.Mesh;
    평면005_2: THREE.Mesh;
    평면005_3: THREE.Mesh;
    평면006_1: THREE.Mesh;
    평면006_2: THREE.Mesh;
    평면007_1: THREE.Mesh;
    평면007_2: THREE.Mesh;
    평면008_1: THREE.Mesh;
    평면008_2: THREE.Mesh;
    평면009_1: THREE.Mesh;
    평면009_2: THREE.Mesh;
    평면: THREE.Mesh;
    평면001: THREE.Mesh;
    평면002: THREE.Mesh;
    평면003: THREE.Mesh;
    평면004: THREE.Mesh;
    평면005: THREE.Mesh;
    평면006: THREE.Mesh;
    평면007: THREE.Mesh;
    평면008: THREE.Mesh;
    평면009: THREE.Mesh;
    평면010: THREE.Mesh;
    평면011: THREE.Mesh;
    boatBody: THREE.Mesh;
    평면003_1: THREE.Mesh;
    평면003_2: THREE.Mesh;
    큐브: THREE.Mesh;
    큐브001: THREE.Mesh;
  };
  materials: {
    ['매테리얼.003']: THREE.MeshStandardMaterial;
    ['매테리얼.004']: THREE.MeshStandardMaterial;
    ['매테리얼.005']: THREE.MeshStandardMaterial;
    ['매테리얼.001']: THREE.MeshStandardMaterial;
    ['매테리얼.006']: THREE.MeshStandardMaterial;
    ['매테리얼.009']: THREE.MeshStandardMaterial;
    ['매테리얼.010']: THREE.MeshStandardMaterial;
    ['매테리얼.002']: THREE.MeshStandardMaterial;
    ['매테리얼.012']: THREE.MeshStandardMaterial;
    ['매테리얼.013']: THREE.MeshStandardMaterial;
    ['매테리얼.014']: THREE.MeshStandardMaterial;
    매테리얼: THREE.MeshStandardMaterial;
  };
};

export function Error404(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.error_404_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.02, 0.17, 0]} scale={2.86}>
        <mesh
          geometry={nodes.아이코스피어_1.geometry}
          material={materials['매테리얼.003']}
        />
        <mesh
          geometry={nodes.아이코스피어_2.geometry}
          material={materials['매테리얼.004']}
        />
        <mesh
          geometry={nodes.아이코스피어_3.geometry}
          material={materials['매테리얼.005']}
        />
      </group>
      <mesh
        geometry={nodes.아이코스피어001.geometry}
        material={materials['매테리얼.001']}
        position={[0.02, 0.17, 0]}
        scale={2.86}
      />
      <mesh
        geometry={nodes.tree.geometry}
        material={materials['매테리얼.006']}
        position={[-0.56, 2.58, 1.66]}
        rotation={[0.62, 0.05, 0.19]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree001.geometry}
        material={materials['매테리얼.006']}
        position={[-0.17, 2.67, 1.62]}
        rotation={[0.58, 0.04, 0.02]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree002.geometry}
        material={materials['매테리얼.006']}
        position={[0.39, 2.48, 1.86]}
        rotation={[0.71, 0.04, -0.11]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree003.geometry}
        material={materials['매테리얼.006']}
        position={[-0.09, 2.44, 1.97]}
        rotation={[0.58, 0.04, 0.02]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree004.geometry}
        material={materials['매테리얼.006']}
        position={[-0.68, 2.07, 2.19]}
        rotation={[0.79, 0.07, 0.23]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.tree005.geometry}
        material={materials['매테리얼.006']}
        position={[0.32, 2.13, 2.24]}
        rotation={[0.88, 0.08, -0.07]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.tree006.geometry}
        material={materials['매테리얼.006']}
        position={[-0.13, 2.02, 2.35]}
        rotation={[0.92, 0.08, 0.1]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree007.geometry}
        material={materials['매테리얼.006']}
        position={[-0.46, 2.37, 1.97]}
        rotation={[0.62, 0.03, 0.19]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree008.geometry}
        material={materials['매테리얼.006']}
        position={[-1.17, 2.09, 1.97]}
        rotation={[0.83, 0.1, 0.4]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree009.geometry}
        material={materials['매테리얼.006']}
        position={[-1.56, 2.06, 1.69]}
        rotation={[0.72, 0.04, 0.53]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree010.geometry}
        material={materials['매테리얼.006']}
        position={[-1.32, 1.65, 2.24]}
        rotation={[0.98, 0.18, 0.44]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree011.geometry}
        material={materials['매테리얼.006']}
        position={[-1.66, 1.36, 2.18]}
        rotation={[1, 0.19, 0.61]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree012.geometry}
        material={materials['매테리얼.006']}
        position={[-1.92, 1.75, 1.65]}
        rotation={[0.77, 0.02, 0.66]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree013.geometry}
        material={materials['매테리얼.006']}
        position={[-1.97, 1.46, 1.84]}
        rotation={[0.91, 0.13, 0.71]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree014.geometry}
        material={materials['매테리얼.006']}
        position={[-1.63, 1.76, 1.96]}
        rotation={[0.77, 0.02, 0.66]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree015.geometry}
        material={materials['매테리얼.006']}
        position={[2.22, 1.91, 1.02]}
        rotation={[0.61, 0.09, -0.82]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree016.geometry}
        material={materials['매테리얼.006']}
        position={[2.44, 1.44, 1.21]}
        rotation={[0.7, -0.02, -0.94]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree017.geometry}
        material={materials['매테리얼.006']}
        position={[2.67, 1.22, 0.89]}
        rotation={[0.68, 0.01, -1.11]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.tree018.geometry}
        material={materials['매테리얼.006']}
        position={[2.74, 1.35, 0.4]}
        rotation={[0.63, 0.13, -1.15]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree019.geometry}
        material={materials['매테리얼.006']}
        position={[2.54, 1.77, 0.27]}
        rotation={[0.56, 0.25, -1.03]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree020.geometry}
        material={materials['매테리얼.006']}
        position={[2.31, 2.03, 0.48]}
        rotation={[0.56, 0.25, -0.89]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree021.geometry}
        material={materials['매테리얼.006']}
        position={[2.54, 1.67, 0.75]}
        rotation={[0.71, 0.02, -1.11]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree022.geometry}
        material={materials['매테리얼.006']}
        position={[-2.61, -0.17, 1.36]}
        rotation={[1.1, 0.32, 1.2]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.tree023.geometry}
        material={materials['매테리얼.006']}
        position={[-2.33, -0.44, 1.73]}
        rotation={[1.18, 0.46, 1.09]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree024.geometry}
        material={materials['매테리얼.006']}
        position={[-2.57, -0.66, 1.32]}
        rotation={[1.96, -0.06, 0.92]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree025.geometry}
        material={materials['매테리얼.006']}
        position={[-2.25, -1.02, 1.52]}
        rotation={[1.71, 0.35, 0.93]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree026.geometry}
        material={materials['매테리얼.006']}
        position={[-2.74, -0.64, 0.84]}
        rotation={[1.18, 0.44, 1.44]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.tree027.geometry}
        material={materials['매테리얼.006']}
        position={[-2.52, -1.14, 0.92]}
        rotation={[-0.42, 0.23, 2.17]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.tree028.geometry}
        material={materials['매테리얼.006']}
        position={[0.93, 0.73, 2.79]}
        rotation={[1.23, -0.48, -0.35]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.tree029.geometry}
        material={materials['매테리얼.006']}
        position={[0.6, 0.41, 2.92]}
        rotation={[1.4, -0.52, -0.18]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.tree030.geometry}
        material={materials['매테리얼.006']}
        position={[1.35, -0.03, 2.66]}
        rotation={[1.39, -0.52, -0.54]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.tree031.geometry}
        material={materials['매테리얼.006']}
        position={[0.99, 0.25, 2.86]}
        rotation={[1.24, -0.45, -0.34]}
        scale={0.05}
      />
      <group
        position={[-0.95, 1.37, 2.75]}
        rotation={[0.84, 0.84, 0.45]}
        scale={[0.19, 0.16, 0.16]}
      >
        <mesh
          geometry={nodes.평면001_1.geometry}
          material={materials['매테리얼.009']}
        />
        <mesh
          geometry={nodes.평면001_2.geometry}
          material={materials['매테리얼.010']}
        />
      </group>
      <group
        position={[1.39, 0.44, 2.64]}
        rotation={[1.03, -0.71, -0.64]}
        scale={[0.19, 0.16, 0.16]}
      >
        <mesh
          geometry={nodes.평면005_1.geometry}
          material={nodes.평면005_1.material}
        />
        <mesh
          geometry={nodes.평면005_2.geometry}
          material={materials['매테리얼.009']}
        />
        <mesh
          geometry={nodes.평면005_3.geometry}
          material={materials['매테리얼.010']}
        />
      </group>
      <group
        position={[2.81, -0.87, 0.05]}
        rotation={[0.8, -0.27, -1.82]}
        scale={[0.19, 0.16, 0.16]}
      >
        <mesh
          geometry={nodes.평면006_1.geometry}
          material={materials['매테리얼.009']}
        />
        <mesh
          geometry={nodes.평면006_2.geometry}
          material={materials['매테리얼.010']}
        />
      </group>
      <group
        position={[-0.37, 1.54, 2.82]}
        rotation={[0.95, 0.87, 0.21]}
        scale={[0.19, 0.16, 0.16]}
      >
        <mesh
          geometry={nodes.평면007_1.geometry}
          material={materials['매테리얼.009']}
        />
        <mesh
          geometry={nodes.평면007_2.geometry}
          material={materials['매테리얼.010']}
        />
      </group>
      <group
        position={[-0.89, 0.84, 3.06]}
        rotation={[-0.37, 1.26, 1.73]}
        scale={[0.19, 0.16, 0.16]}
      >
        <mesh
          geometry={nodes.평면008_1.geometry}
          material={materials['매테리얼.009']}
        />
        <mesh
          geometry={nodes.평면008_2.geometry}
          material={materials['매테리얼.010']}
        />
      </group>
      <group
        position={[0.05, 1.22, 2.98]}
        rotation={[1.22, 0.14, -0.01]}
        scale={[0.19, 0.16, 0.16]}
      >
        <mesh
          geometry={nodes.평면009_1.geometry}
          material={materials['매테리얼.009']}
        />
        <mesh
          geometry={nodes.평면009_2.geometry}
          material={materials['매테리얼.010']}
        />
      </group>
      <mesh
        geometry={nodes.평면.geometry}
        material={materials['매테리얼.002']}
        position={[-2.14, 1.97, -1.05]}
        rotation={[-0.17, -0.27, 0.83]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.평면001.geometry}
        material={materials['매테리얼.002']}
        position={[-2.59, 1.61, -0.29]}
        rotation={[-2.61, 0.38, 1.88]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.평면002.geometry}
        material={materials['매테리얼.002']}
        position={[-2.73, 0.78, -1]}
        rotation={[-0.13, -0.29, 1.35]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.평면003.geometry}
        material={materials['매테리얼.002']}
        position={[-2.89, 0.84, 0.08]}
        rotation={[2.45, -0.12, 1.72]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.평면004.geometry}
        material={materials['매테리얼.002']}
        position={[-0.69, 1.22, -2.71]}
        rotation={[-0.91, -0.75, 0.4]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.평면005.geometry}
        material={materials['매테리얼.002']}
        position={[0.15, 0.73, -2.94]}
        rotation={[1.75, -0.49, 3.14]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.평면006.geometry}
        material={materials['매테리얼.002']}
        position={[1.47, 0.38, -2.68]}
        rotation={[1.9, -0.45, -2.62]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.평면007.geometry}
        material={materials['매테리얼.002']}
        position={[2.13, -0.07, -2.19]}
        rotation={[-1.84, -0.16, -0.79]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.평면008.geometry}
        material={materials['매테리얼.002']}
        position={[0.48, -1.08, -2.75]}
        rotation={[1.24, -0.74, -2.96]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.평면009.geometry}
        material={materials['매테리얼.002']}
        position={[1.68, -1.56, -1.91]}
        rotation={[0.54, 0.33, -2.57]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.평면010.geometry}
        material={materials['매테리얼.002']}
        position={[2.94, -0.39, 0.11]}
        rotation={[-1.99, 0.17, -1.5]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.평면011.geometry}
        material={materials['매테리얼.002']}
        position={[2.68, -0.88, 0.85]}
        rotation={[-0.81, 0.05, -2.05]}
        scale={0.03}
      />
      <mesh
        geometry={nodes.boatBody.geometry}
        material={materials['매테리얼.012']}
        position={[0.45, 2.96, 0.88]}
        rotation={[0.3, -0.26, -0.22]}
        scale={[0.73, 1.28, 0.23]}
      />
      <group
        position={[0.46, 2.94, 0.93]}
        rotation={[0.29, -0.32, -0.22]}
        scale={[0.03, 0.05, 0.03]}
      >
        <mesh
          geometry={nodes.평면003_1.geometry}
          material={materials['매테리얼.013']}
        />
        <mesh
          geometry={nodes.평면003_2.geometry}
          material={materials['매테리얼.014']}
        />
      </group>
      <mesh
        geometry={nodes.큐브.geometry}
        material={materials.매테리얼}
        position={[2, -1.85, 3.17]}
        rotation={[0.14, 0, 0.01]}
        scale={[0.92, 2.02, 0.92]}
      />
      <mesh
        geometry={nodes.큐브001.geometry}
        material={materials.매테리얼}
        position={[3, -1.76, -5.49]}
        rotation={[-0.07, -0.01, 0.15]}
        scale={[0.63, 1.39, 0.63]}
      />
    </group>
  );
}

useGLTF.preload(glbs.error_404_glb);
