/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 house_1.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    평면004: THREE.Mesh;
    평면004_1: THREE.Mesh;
    평면004_2: THREE.Mesh;
  };
  materials: {
    ['매테리얼.002']: THREE.MeshStandardMaterial;
    ['Dark Wood']: THREE.MeshStandardMaterial;
    HI: THREE.MeshStandardMaterial;
  };
};

export function House_1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'https://storage.googleapis.com/churest-bucket/project_3D/house_1.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.평면004.geometry}
        material={materials['매테리얼.002']}
      />
      <mesh
        geometry={nodes.평면004_1.geometry}
        material={materials['Dark Wood']}
      />
      <mesh geometry={nodes.평면004_2.geometry} material={materials.HI} />
    </group>
  );
}

useGLTF.preload('/house_1.glb');
