/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 loginEarth.glb -t
*/

import * as THREE from 'three';
import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    아이코스피어_1: THREE.Mesh;
    아이코스피어_2: THREE.Mesh;
    아이코스피어001: THREE.Mesh;
    tree: THREE.Mesh;
    tree001: THREE.Mesh;
    tree002: THREE.Mesh;
    tree003: THREE.Mesh;
    tree004: THREE.Mesh;
    tree005: THREE.Mesh;
    tree006: THREE.Mesh;
    tree007: THREE.Mesh;
    tree008: THREE.Mesh;
    tree009: THREE.Mesh;
    tree010: THREE.Mesh;
    tree011: THREE.Mesh;
    tree012: THREE.Mesh;
    tree013: THREE.Mesh;
    tree014: THREE.Mesh;
    tree015: THREE.Mesh;
    tree016: THREE.Mesh;
    tree017: THREE.Mesh;
    tree018: THREE.Mesh;
    tree019: THREE.Mesh;
    tree020: THREE.Mesh;
    tree021: THREE.Mesh;
    tree022: THREE.Mesh;
    tree023: THREE.Mesh;
    tree024: THREE.Mesh;
    tree025: THREE.Mesh;
    tree026: THREE.Mesh;
    tree027: THREE.Mesh;
    tree028: THREE.Mesh;
    tree029: THREE.Mesh;
    tree030: THREE.Mesh;
    tree031: THREE.Mesh;
    평면001_1: THREE.Mesh;
    평면001_2: THREE.Mesh;
    평면005_1: THREE.Mesh;
    평면005_2: THREE.Mesh;
    평면005_3: THREE.Mesh;
    평면006_1: THREE.Mesh;
    평면006_2: THREE.Mesh;
    평면007_1: THREE.Mesh;
    평면007_2: THREE.Mesh;
    평면008_1: THREE.Mesh;
    평면008_2: THREE.Mesh;
    평면009_1: THREE.Mesh;
    평면009_2: THREE.Mesh;
    평면: THREE.Mesh;
    평면001: THREE.Mesh;
    평면002: THREE.Mesh;
    평면003: THREE.Mesh;
    평면004: THREE.Mesh;
    평면005: THREE.Mesh;
    평면006: THREE.Mesh;
    평면007: THREE.Mesh;
    평면008: THREE.Mesh;
    평면009: THREE.Mesh;
    평면010: THREE.Mesh;
    평면011: THREE.Mesh;
    boatBody: THREE.Mesh;
    평면003_1: THREE.Mesh;
    평면003_2: THREE.Mesh;
    아이코스피어002: THREE.Mesh;
    아이코스피어003: THREE.Mesh;
    아이코스피어004: THREE.Mesh;
    아이코스피어005: THREE.Mesh;
    아이코스피어006: THREE.Mesh;
    아이코스피어007: THREE.Mesh;
    아이코스피어008: THREE.Mesh;
    아이코스피어009: THREE.Mesh;
    아이코스피어010: THREE.Mesh;
  };
  materials: {
    ['매테리얼.002']: THREE.MeshStandardMaterial;
    ['매테리얼.004']: THREE.MeshStandardMaterial;
    ['매테리얼.001']: THREE.MeshStandardMaterial;
    ['매테리얼.006']: THREE.MeshStandardMaterial;
    ['매테리얼.009']: THREE.MeshStandardMaterial;
    ['매테리얼.010']: THREE.MeshStandardMaterial;
    매테리얼: THREE.MeshStandardMaterial;
    ['매테리얼.012']: THREE.MeshStandardMaterial;
    ['매테리얼.013']: THREE.MeshStandardMaterial;
    ['매테리얼.014']: THREE.MeshStandardMaterial;
  };
};

export function LoginEarth(props: JSX.IntrinsicElements['group']) {
  // const { nodes, materials } = useGLTF(
  //   'https://storage.cloud.google.com/churest-bucket/loginEarth.glb'
  // ) as GLTFResult;
  const { nodes, materials } = useGLTF('/3Dglb/loginEarth.glb') as GLTFResult;
  const [angle, setAngle] = useState(0);
  useFrame(() => {
    setAngle((prev) => prev + 1);
  });

  return (
    <group {...props} dispose={null} rotation={[0, (Math.PI / 360) * angle, 0]}>
      <mesh
        geometry={nodes.아이코스피어001.geometry}
        material={materials['매테리얼.001']}
        // castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree.geometry}
        material={materials['매테리얼.006']}
        position={[-0.2, 0.84, 0.58]}
        rotation={[0.62, 0.05, 0.19]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree001.geometry}
        material={materials['매테리얼.006']}
        position={[-0.06, 0.88, 0.57]}
        rotation={[0.58, 0.04, 0.02]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree002.geometry}
        material={materials['매테리얼.006']}
        position={[0.13, 0.81, 0.65]}
        rotation={[0.71, 0.04, -0.11]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree003.geometry}
        material={materials['매테리얼.006']}
        position={[-0.04, 0.79, 0.69]}
        rotation={[0.58, 0.04, 0.02]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree004.geometry}
        material={materials['매테리얼.006']}
        position={[-0.24, 0.67, 0.77]}
        rotation={[0.79, 0.07, 0.23]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree005.geometry}
        material={materials['매테리얼.006']}
        position={[0.1, 0.69, 0.78]}
        rotation={[0.88, 0.08, -0.07]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree006.geometry}
        material={materials['매테리얼.006']}
        position={[-0.05, 0.64, 0.82]}
        rotation={[0.92, 0.08, 0.1]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree007.geometry}
        material={materials['매테리얼.006']}
        position={[-0.17, 0.77, 0.69]}
        rotation={[0.62, 0.03, 0.19]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree008.geometry}
        material={materials['매테리얼.006']}
        position={[-0.41, 0.67, 0.69]}
        rotation={[0.83, 0.1, 0.4]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree009.geometry}
        material={materials['매테리얼.006']}
        position={[-0.55, 0.66, 0.59]}
        rotation={[0.72, 0.04, 0.53]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree010.geometry}
        material={materials['매테리얼.006']}
        position={[-0.47, 0.52, 0.78]}
        rotation={[0.98, 0.18, 0.44]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree011.geometry}
        material={materials['매테리얼.006']}
        position={[-0.59, 0.41, 0.76]}
        rotation={[1, 0.19, 0.61]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree012.geometry}
        material={materials['매테리얼.006']}
        position={[-0.68, 0.55, 0.58]}
        rotation={[0.77, 0.02, 0.66]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree013.geometry}
        material={materials['매테리얼.006']}
        position={[-0.69, 0.45, 0.64]}
        rotation={[0.91, 0.13, 0.71]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree014.geometry}
        material={materials['매테리얼.006']}
        position={[-0.58, 0.55, 0.69]}
        rotation={[0.77, 0.02, 0.66]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree015.geometry}
        material={materials['매테리얼.006']}
        position={[0.77, 0.61, 0.36]}
        rotation={[0.61, 0.09, -0.82]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree016.geometry}
        material={materials['매테리얼.006']}
        position={[0.85, 0.44, 0.42]}
        rotation={[0.7, -0.02, -0.94]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree017.geometry}
        material={materials['매테리얼.006']}
        position={[0.93, 0.37, 0.31]}
        rotation={[0.68, 0.01, -1.11]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree018.geometry}
        material={materials['매테리얼.006']}
        position={[0.95, 0.41, 0.14]}
        rotation={[0.63, 0.13, -1.15]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree019.geometry}
        material={materials['매테리얼.006']}
        position={[0.88, 0.56, 0.09]}
        rotation={[0.56, 0.25, -1.03]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree020.geometry}
        material={materials['매테리얼.006']}
        position={[0.8, 0.65, 0.17]}
        rotation={[0.56, 0.25, -0.89]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree021.geometry}
        material={materials['매테리얼.006']}
        position={[0.88, 0.52, 0.26]}
        rotation={[0.71, 0.02, -1.11]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree022.geometry}
        material={materials['매테리얼.006']}
        position={[-0.92, -0.12, 0.48]}
        rotation={[1.1, 0.32, 1.2]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree023.geometry}
        material={materials['매테리얼.006']}
        position={[-0.82, -0.21, 0.61]}
        rotation={[1.18, 0.46, 1.09]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree024.geometry}
        material={materials['매테리얼.006']}
        position={[-0.91, -0.29, 0.46]}
        rotation={[1.96, -0.06, 0.92]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree025.geometry}
        material={materials['매테리얼.006']}
        position={[-0.8, -0.42, 0.53]}
        rotation={[1.71, 0.35, 0.93]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree026.geometry}
        material={materials['매테리얼.006']}
        position={[-0.97, -0.28, 0.29]}
        rotation={[1.18, 0.44, 1.44]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree027.geometry}
        material={materials['매테리얼.006']}
        position={[-0.89, -0.46, 0.32]}
        rotation={[-0.42, 0.23, 2.17]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree028.geometry}
        material={materials['매테리얼.006']}
        position={[0.32, 0.2, 0.98]}
        rotation={[1.23, -0.48, -0.35]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree029.geometry}
        material={materials['매테리얼.006']}
        position={[0.2, 0.08, 1.02]}
        rotation={[1.4, -0.52, -0.18]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree030.geometry}
        material={materials['매테리얼.006']}
        position={[0.47, -0.07, 0.93]}
        rotation={[1.39, -0.52, -0.54]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.tree031.geometry}
        material={materials['매테리얼.006']}
        position={[0.34, 0.03, 1]}
        rotation={[1.24, -0.45, -0.34]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <group
        position={[-0.34, 0.42, 0.96]}
        rotation={[0.84, 0.84, 0.45]}
        scale={[0.07, 0.06, 0.06]}
      >
        <mesh
          geometry={nodes.평면001_1.geometry}
          material={materials['매테리얼.009']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면001_2.geometry}
          material={materials['매테리얼.010']}
          castShadow
          receiveShadow
        />
      </group>
      <group
        position={[0.48, 0.09, 0.92]}
        rotation={[1.03, -0.71, -0.64]}
        scale={[0.07, 0.06, 0.06]}
      >
        <mesh
          geometry={nodes.평면005_1.geometry}
          material={nodes.평면005_1.material}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면005_2.geometry}
          material={materials['매테리얼.009']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면005_3.geometry}
          material={materials['매테리얼.010']}
          castShadow
          receiveShadow
        />
      </group>
      <group
        position={[0.98, -0.36, 0.02]}
        rotation={[0.8, -0.27, -1.82]}
        scale={[0.07, 0.06, 0.06]}
      >
        <mesh
          geometry={nodes.평면006_1.geometry}
          material={materials['매테리얼.009']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면006_2.geometry}
          material={materials['매테리얼.010']}
          castShadow
          receiveShadow
        />
      </group>
      <group
        position={[-0.13, 0.48, 0.99]}
        rotation={[0.95, 0.87, 0.21]}
        scale={[0.07, 0.06, 0.06]}
      >
        <mesh
          geometry={nodes.평면007_1.geometry}
          material={materials['매테리얼.009']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면007_2.geometry}
          material={materials['매테리얼.010']}
          castShadow
          receiveShadow
        />
      </group>
      <group
        position={[-0.32, 0.23, 1.07]}
        rotation={[-0.37, 1.26, 1.73]}
        scale={[0.07, 0.06, 0.06]}
      >
        <mesh
          geometry={nodes.평면008_1.geometry}
          material={materials['매테리얼.009']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면008_2.geometry}
          material={materials['매테리얼.010']}
          castShadow
          receiveShadow
        />
      </group>
      <group
        position={[0.01, 0.37, 1.04]}
        rotation={[1.22, 0.14, -0.01]}
        scale={[0.07, 0.06, 0.06]}
      >
        <mesh
          geometry={nodes.평면009_1.geometry}
          material={materials['매테리얼.009']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면009_2.geometry}
          material={materials['매테리얼.010']}
          castShadow
          receiveShadow
        />
      </group>
      <mesh
        geometry={nodes.평면.geometry}
        material={materials.매테리얼}
        position={[-0.75, 0.63, -0.37]}
        rotation={[-0.17, -0.27, 0.83]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면001.geometry}
        material={materials.매테리얼}
        position={[-0.91, 0.5, -0.1]}
        rotation={[-2.61, 0.38, 1.88]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면002.geometry}
        material={materials.매테리얼}
        position={[-0.96, 0.21, -0.35]}
        rotation={[-0.13, -0.29, 1.35]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면003.geometry}
        material={materials.매테리얼}
        position={[-1.02, 0.23, 0.03]}
        rotation={[2.45, -0.12, 1.72]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면004.geometry}
        material={materials.매테리얼}
        position={[-0.25, 0.37, -0.95]}
        rotation={[-0.91, -0.75, 0.4]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면005.geometry}
        material={materials.매테리얼}
        position={[0.05, 0.19, -1.03]}
        rotation={[1.75, -0.49, 3.14]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면006.geometry}
        material={materials.매테리얼}
        position={[0.51, 0.07, -0.94]}
        rotation={[1.9, -0.45, -2.62]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면007.geometry}
        material={materials.매테리얼}
        position={[0.74, -0.08, -0.77]}
        rotation={[-1.84, -0.16, -0.79]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면008.geometry}
        material={materials.매테리얼}
        position={[0.16, -0.44, -0.96]}
        rotation={[1.24, -0.74, -2.96]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면009.geometry}
        material={materials.매테리얼}
        position={[0.58, -0.61, -0.67]}
        rotation={[0.54, 0.33, -2.57]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면010.geometry}
        material={materials.매테리얼}
        position={[1.02, -0.2, 0.04]}
        rotation={[-1.99, 0.17, -1.5]}
        scale={0.02}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.평면011.geometry}
        material={materials.매테리얼}
        position={[0.93, -0.37, 0.3]}
        rotation={[-0.81, 0.05, -2.05]}
        scale={0.01}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.boatBody.geometry}
        material={materials['매테리얼.012']}
        position={[0.15, 0.97, 0.31]}
        rotation={[0.3, -0.26, -0.22]}
        scale={[0.25, 0.45, 0.08]}
        castShadow
        receiveShadow
      />
      <group
        position={[0.16, 0.97, 0.33]}
        rotation={[0.29, -0.32, -0.22]}
        scale={[0.01, 0.02, 0.01]}
      >
        <mesh
          geometry={nodes.평면003_1.geometry}
          material={materials['매테리얼.013']}
          castShadow
          receiveShadow
        />
        <mesh
          geometry={nodes.평면003_2.geometry}
          material={materials['매테리얼.014']}
          castShadow
          receiveShadow
        />
      </group>
      <mesh
        geometry={nodes.아이코스피어002.geometry}
        material={materials['매테리얼.009']}
        position={[0.06, 1.38, 0.07]}
        rotation={[0.02, 0, -0.06]}
        scale={0.13}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어003.geometry}
        material={materials['매테리얼.009']}
        position={[0.17, 1.33, 0.03]}
        rotation={[0.02, 0, -0.06]}
        scale={0.09}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어004.geometry}
        material={materials['매테리얼.009']}
        position={[-0.07, 1.39, 0.06]}
        rotation={[0.02, 0, -0.06]}
        scale={0.09}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어005.geometry}
        material={materials['매테리얼.009']}
        position={[-0.85, -1.04, 0.87]}
        rotation={[1.19, 1.45, 1.45]}
        scale={0.15}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어006.geometry}
        material={materials['매테리얼.009']}
        position={[-0.89, -0.93, 0.95]}
        rotation={[1.19, 1.45, 1.45]}
        scale={0.1}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어007.geometry}
        material={materials['매테리얼.009']}
        position={[-0.87, -1.11, 0.74]}
        rotation={[1.19, 1.45, 1.45]}
        scale={0.11}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어008.geometry}
        material={materials['매테리얼.009']}
        position={[1.03, 1.12, -0.18]}
        rotation={[0.23, -0.86, 2.93]}
        scale={0.13}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어009.geometry}
        material={materials['매테리얼.009']}
        position={[1, 1.21, -0.26]}
        rotation={[0.23, -0.86, 2.93]}
        scale={0.09}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어010.geometry}
        material={materials['매테리얼.009']}
        position={[1.12, 1.07, -0.1]}
        rotation={[0.23, -0.86, 2.93]}
        scale={0.09}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어_1.geometry}
        material={materials['매테리얼.002']}
        // castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.아이코스피어_2.geometry}
        material={materials['매테리얼.004']}
        // castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload('/3Dglb/loginEarth.glb');
