/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 PostBox.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    Torus_1: THREE.Mesh;
    Torus_2: THREE.Mesh;
    Torus_3: THREE.Mesh;
    Torus_4: THREE.Mesh;
    Torus_5: THREE.Mesh;
    Torus_6: THREE.Mesh;
    Torus_7: THREE.Mesh;
    Torus_8: THREE.Mesh;
    Torus_9: THREE.Mesh;
    Torus_10: THREE.Mesh;
    Torus_11: THREE.Mesh;
    Torus_12: THREE.Mesh;
    Torus_13: THREE.Mesh;
    Torus_14: THREE.Mesh;
    Torus_15: THREE.Mesh;
    Torus_16: THREE.Mesh;
    Torus_17: THREE.Mesh;
  };
  materials: {
    ['매테리얼.025']: THREE.MeshStandardMaterial;
    ['매테리얼.007']: THREE.MeshStandardMaterial;
    ['매테리얼.008']: THREE.MeshStandardMaterial;
    ['매테리얼.010']: THREE.MeshStandardMaterial;
    ['매테리얼.015']: THREE.MeshStandardMaterial;
    ['매테리얼.017']: THREE.MeshStandardMaterial;
    ['매테리얼.018']: THREE.MeshStandardMaterial;
    ['매테리얼.019']: THREE.MeshStandardMaterial;
    ['매테리얼.020']: THREE.MeshStandardMaterial;
    ['매테리얼.021']: THREE.MeshStandardMaterial;
    ['매테리얼.022']: THREE.MeshStandardMaterial;
    ['매테리얼.023']: THREE.MeshStandardMaterial;
    ['매테리얼.024']: THREE.MeshStandardMaterial;
    ['매테리얼.026']: THREE.MeshStandardMaterial;
    ['매테리얼.027']: THREE.MeshStandardMaterial;
    ['매테리얼.028']: THREE.MeshStandardMaterial;
    ['매테리얼.029']: THREE.MeshStandardMaterial;
  };
};

export function PostBox(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.post_box_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0, 0.42, -0.48]}
        rotation={[-1.01, 0, -Math.PI / 2]}
        scale={0.03}
      >
        <mesh
          geometry={nodes.Torus_1.geometry}
          material={materials['매테리얼.025']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_2.geometry}
          material={materials['매테리얼.007']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_3.geometry}
          material={materials['매테리얼.008']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_4.geometry}
          material={materials['매테리얼.010']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_5.geometry}
          material={materials['매테리얼.015']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_6.geometry}
          material={materials['매테리얼.017']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_7.geometry}
          material={materials['매테리얼.018']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_8.geometry}
          material={materials['매테리얼.019']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_9.geometry}
          material={materials['매테리얼.020']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_10.geometry}
          material={materials['매테리얼.021']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_11.geometry}
          material={materials['매테리얼.022']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_12.geometry}
          material={materials['매테리얼.023']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_13.geometry}
          material={materials['매테리얼.024']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_14.geometry}
          material={materials['매테리얼.026']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_15.geometry}
          material={materials['매테리얼.027']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_16.geometry}
          material={materials['매테리얼.028']}
          castShadow
        />
        <mesh
          geometry={nodes.Torus_17.geometry}
          material={materials['매테리얼.029']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.post_box_glb);
