/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 SquareMap.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';
import { RigidBody } from '@react-three/rapier';

type GLTFResult = GLTF & {
  nodes: {
    tree1: THREE.Mesh;
    tree1001: THREE.Mesh;
    tree1002: THREE.Mesh;
    tree1003: THREE.Mesh;
    tree1004: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Sphere003_1: THREE.Mesh;
    Sphere003_2: THREE.Mesh;
    Sphere003_3: THREE.Mesh;
    Sphere003_4: THREE.Mesh;
    Sphere003_5: THREE.Mesh;
    Sphere003_6: THREE.Mesh;
    Sphere001: THREE.Mesh;
    Sphere001_1: THREE.Mesh;
    Sphere001_2: THREE.Mesh;
    Sphere001_3: THREE.Mesh;
    Sphere001_4: THREE.Mesh;
    Sphere001_5: THREE.Mesh;
    Sphere001_6: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    Cube003_2: THREE.Mesh;
    Cube003_3: THREE.Mesh;
    Cube003_4: THREE.Mesh;
    Cube003_5: THREE.Mesh;
    Cube003_6: THREE.Mesh;
    Cube003_7: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    Cube002_3: THREE.Mesh;
    Cube002_4: THREE.Mesh;
    Cube002_5: THREE.Mesh;
    Sphere008: THREE.Mesh;
    Sphere008_1: THREE.Mesh;
    Sphere008_2: THREE.Mesh;
    Sphere008_3: THREE.Mesh;
    Sphere008_4: THREE.Mesh;
    Sphere008_5: THREE.Mesh;
    Sphere008_6: THREE.Mesh;
    Mesh1749: THREE.Mesh;
    Mesh1749_1: THREE.Mesh;
    Mesh002: THREE.Mesh;
    Mesh002_1: THREE.Mesh;
    Mesh025: THREE.Mesh;
    Mesh025_1: THREE.Mesh;
    Mesh026: THREE.Mesh;
    Mesh026_1: THREE.Mesh;
    Mesh029: THREE.Mesh;
    Mesh029_1: THREE.Mesh;
    Mesh091: THREE.Mesh;
    Mesh091_1: THREE.Mesh;
    Mesh092: THREE.Mesh;
    Mesh092_1: THREE.Mesh;
    큐브_1: THREE.Mesh;
    큐브_2: THREE.Mesh;
    큐브_3: THREE.Mesh;
    큐브001: THREE.Mesh;
    실린더003: THREE.Mesh;
    큐브002: THREE.Mesh;
    실린더: THREE.Mesh;
    실린더001: THREE.Mesh;
    실린더002: THREE.Mesh;
    평면: THREE.Mesh;
    평면001: THREE.Mesh;
    원형_1: THREE.Mesh;
    원형_2: THREE.Mesh;
    fantasy_plant053: THREE.Mesh;
    stone020: THREE.Mesh;
    stone001: THREE.Mesh;
    building015: THREE.Mesh;
    building012: THREE.Mesh;
    building011: THREE.Mesh;
    prop032: THREE.Mesh;
    prop006: THREE.Mesh;
    fantasy_plant190: THREE.Mesh;
    fantasy_plant003: THREE.Mesh;
    fantasy_plant004: THREE.Mesh;
    fantasy_plant127: THREE.Mesh;
    fantasy_plant005: THREE.Mesh;
    fantasy_plant117: THREE.Mesh;
    fantasy_plant006: THREE.Mesh;
    fantasy_plant007: THREE.Mesh;
    mushroom004: THREE.Mesh;
    mushroom001: THREE.Mesh;
    mushroom010: THREE.Mesh;
    prop054: THREE.Mesh;
    prop053: THREE.Mesh;
    prop001: THREE.Mesh;
    fantasy_plant020: THREE.Mesh;
    fantasy_plant008: THREE.Mesh;
    fantasy_plant009: THREE.Mesh;
    fantasy_plant010: THREE.Mesh;
    fantasy_plant011: THREE.Mesh;
    prop046: THREE.Mesh;
    mushroom076: THREE.Mesh;
    mushroom002: THREE.Mesh;
    mushroom003: THREE.Mesh;
    fantasy_plant503: THREE.Mesh;
    fantasy_plant015: THREE.Mesh;
    fantasy_plant016: THREE.Mesh;
    fantasy_plant017: THREE.Mesh;
    fantasy_plant023: THREE.Mesh;
    fantasy_plant024: THREE.Mesh;
    fantasy_plant025: THREE.Mesh;
    fantasy_plant026: THREE.Mesh;
    fantasy_plant027: THREE.Mesh;
    fantasy_plant028: THREE.Mesh;
    fantasy_plant029: THREE.Mesh;
    stone003: THREE.Mesh;
    stone002: THREE.Mesh;
    stone004: THREE.Mesh;
    stone005: THREE.Mesh;
    stone006: THREE.Mesh;
    stone007: THREE.Mesh;
    stone008: THREE.Mesh;
    stone009: THREE.Mesh;
    stone010: THREE.Mesh;
    stone011: THREE.Mesh;
    stone012: THREE.Mesh;
    stone013: THREE.Mesh;
    stone014: THREE.Mesh;
    stone015: THREE.Mesh;
    stone016: THREE.Mesh;
    stone017: THREE.Mesh;
    stone018: THREE.Mesh;
    stone019: THREE.Mesh;
    stone024: THREE.Mesh;
    tree037: THREE.Mesh;
    tree001: THREE.Mesh;
    tree002: THREE.Mesh;
    tree003: THREE.Mesh;
    stone023: THREE.Mesh;
    fantasy_plant047: THREE.Mesh;
    fantasy_plant032: THREE.Mesh;
    fantasy_plant033: THREE.Mesh;
    tree005: THREE.Mesh;
    tree004: THREE.Mesh;
    fantasy_plant034: THREE.Mesh;
    fantasy_plant035: THREE.Mesh;
    fantasy_plant036: THREE.Mesh;
    fantasy_plant038: THREE.Mesh;
    fantasy_plant039: THREE.Mesh;
    fantasy_plant040: THREE.Mesh;
    fantasy_plant041: THREE.Mesh;
    fantasy_plant054: THREE.Mesh;
    fantasy_plant042: THREE.Mesh;
    fantasy_plant043: THREE.Mesh;
    fantasy_plant044: THREE.Mesh;
    fantasy_plant045: THREE.Mesh;
    fantasy_plant046: THREE.Mesh;
    prop062: THREE.Mesh;
    prop073: THREE.Mesh;
    prop002: THREE.Mesh;
    prop003: THREE.Mesh;
    prop004: THREE.Mesh;
    prop074: THREE.Mesh;
    prop017: THREE.Mesh;
    prop005: THREE.Mesh;
    building001: THREE.Mesh;
    prop064: THREE.Mesh;
    prop007: THREE.Mesh;
    prop008: THREE.Mesh;
    fantasy_plant001: THREE.Mesh;
    fantasy_plant002: THREE.Mesh;
    fantasy_plant048: THREE.Mesh;
    fantasy_plant049: THREE.Mesh;
    fantasy_plant037: THREE.Mesh;
    animal006: THREE.Mesh;
    animal001: THREE.Mesh;
    animal009: THREE.Mesh;
    animal011: THREE.Mesh;
    fantasy_plant075: THREE.Mesh;
    fantasy_plant050: THREE.Mesh;
    fantasy_plant051: THREE.Mesh;
    fantasy_plant071: THREE.Mesh;
    fantasy_plant052: THREE.Mesh;
    fantasy_plant055: THREE.Mesh;
    Mesh093: THREE.Mesh;
    Mesh093_1: THREE.Mesh;
    Mesh093_2: THREE.Mesh;
    Mesh099: THREE.Mesh;
    Mesh099_1: THREE.Mesh;
    Mesh099_2: THREE.Mesh;
    Mesh100: THREE.Mesh;
    Mesh100_1: THREE.Mesh;
    Mesh100_2: THREE.Mesh;
    Mesh101: THREE.Mesh;
    Mesh101_1: THREE.Mesh;
    Mesh101_2: THREE.Mesh;
    Mesh102: THREE.Mesh;
    Mesh102_1: THREE.Mesh;
    Mesh102_2: THREE.Mesh;
    Mesh103: THREE.Mesh;
    Mesh103_1: THREE.Mesh;
    Mesh103_2: THREE.Mesh;
    Mesh104: THREE.Mesh;
    Mesh104_1: THREE.Mesh;
    Mesh104_2: THREE.Mesh;
    Mesh105: THREE.Mesh;
    Mesh105_1: THREE.Mesh;
    Mesh105_2: THREE.Mesh;
    fantasy_plant061: THREE.Mesh;
    fantasy_plant062: THREE.Mesh;
    fantasy_plant063: THREE.Mesh;
    fantasy_plant064: THREE.Mesh;
    fantasy_plant065: THREE.Mesh;
    fantasy_plant066: THREE.Mesh;
    fantasy_plant067: THREE.Mesh;
    fantasy_plant068: THREE.Mesh;
  };
  materials: {
    ['Material.021']: THREE.MeshStandardMaterial;
    ['Material.037']: THREE.MeshStandardMaterial;
    ['Material.038']: THREE.MeshStandardMaterial;
    ['Material.039']: THREE.MeshStandardMaterial;
    ['Material.040']: THREE.MeshStandardMaterial;
    ['Material.041']: THREE.MeshStandardMaterial;
    ['Material.042']: THREE.MeshStandardMaterial;
    ['Material.043']: THREE.MeshStandardMaterial;
    ['Material.044']: THREE.MeshStandardMaterial;
    ['Material.045']: THREE.MeshStandardMaterial;
    ['Material.046']: THREE.MeshStandardMaterial;
    ['Material.047']: THREE.MeshStandardMaterial;
    ['Material.048']: THREE.MeshStandardMaterial;
    ['Material.049']: THREE.MeshStandardMaterial;
    ['Material.050']: THREE.MeshStandardMaterial;
    ['매테리얼.020']: THREE.MeshStandardMaterial;
    ['매테리얼.021']: THREE.MeshStandardMaterial;
    ['Material.051']: THREE.MeshStandardMaterial;
    ['Material.052']: THREE.MeshStandardMaterial;
    ['Material.053']: THREE.MeshStandardMaterial;
    ['Material.054']: THREE.MeshStandardMaterial;
    ['Material.055']: THREE.MeshStandardMaterial;
    ['Material.056']: THREE.MeshStandardMaterial;
    ['Material.074']: THREE.MeshStandardMaterial;
    ['Material.075']: THREE.MeshStandardMaterial;
    ['Material.076']: THREE.MeshStandardMaterial;
    ['Material.077']: THREE.MeshStandardMaterial;
    ['Material.078']: THREE.MeshStandardMaterial;
    ['Material.079']: THREE.MeshStandardMaterial;
    ['Material.080']: THREE.MeshStandardMaterial;
    ['Material.081']: THREE.MeshStandardMaterial;
    ['Material.082']: THREE.MeshStandardMaterial;
    ['Material.083']: THREE.MeshStandardMaterial;
    ['Material.084']: THREE.MeshStandardMaterial;
    ['Material.085']: THREE.MeshStandardMaterial;
    ['Material.086']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['매테리얼.026']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['매테리얼.027']: THREE.MeshStandardMaterial;
    ['매테리얼.017']: THREE.MeshStandardMaterial;
    ['매테리얼.018']: THREE.MeshStandardMaterial;
    ['매테리얼.019']: THREE.MeshStandardMaterial;
    매테리얼: THREE.MeshStandardMaterial;
    ['매테리얼.013']: THREE.MeshStandardMaterial;
    ['매테리얼.008']: THREE.MeshStandardMaterial;
    ['매테리얼.003']: THREE.MeshStandardMaterial;
    ['매테리얼.014']: THREE.MeshStandardMaterial;
    ['매테리얼.016']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.004']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
    ['Material.006']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
    ['Material.008']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
    ['Material.011']: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
    ['Material.014']: THREE.MeshStandardMaterial;
    ['Material.015']: THREE.MeshStandardMaterial;
    ['Material.016']: THREE.MeshStandardMaterial;
    ['Material.017']: THREE.MeshStandardMaterial;
    ['Material.018']: THREE.MeshStandardMaterial;
    ['Material.019']: THREE.MeshStandardMaterial;
    ['Material.022']: THREE.MeshStandardMaterial;
    ['Material.023']: THREE.MeshStandardMaterial;
    ['Material.025']: THREE.MeshStandardMaterial;
    ['Material.026']: THREE.MeshStandardMaterial;
    ['Material.028']: THREE.MeshStandardMaterial;
    ['Material.029']: THREE.MeshStandardMaterial;
    ['Material.030']: THREE.MeshStandardMaterial;
    ['Material.035']: THREE.MeshStandardMaterial;
    ['Material.036']: THREE.MeshStandardMaterial;
    ['Material.057']: THREE.MeshStandardMaterial;
    ['Material.058']: THREE.MeshStandardMaterial;
    ['Material.059']: THREE.MeshStandardMaterial;
    ['Material.060']: THREE.MeshStandardMaterial;
    ['Material.064']: THREE.MeshStandardMaterial;
    ['Material.065']: THREE.MeshStandardMaterial;
    ['Material.067']: THREE.MeshStandardMaterial;
    ['Material.068']: THREE.MeshStandardMaterial;
    ['Material.069']: THREE.MeshStandardMaterial;
    ['Material.070']: THREE.MeshStandardMaterial;
    ['Material.071']: THREE.MeshStandardMaterial;
    ['Material.072']: THREE.MeshStandardMaterial;
    ['Material.073']: THREE.MeshStandardMaterial;
    ['Material.087']: THREE.MeshStandardMaterial;
    ['Material.088']: THREE.MeshStandardMaterial;
    ['Material.089']: THREE.MeshStandardMaterial;
    ['Material.090']: THREE.MeshStandardMaterial;
    ['Material.091']: THREE.MeshStandardMaterial;
    ['Material.092']: THREE.MeshStandardMaterial;
    ['Material.093']: THREE.MeshStandardMaterial;
    ['매테리얼.028']: THREE.MeshStandardMaterial;
    ['Material.031']: THREE.MeshStandardMaterial;
    ['매테리얼.029']: THREE.MeshStandardMaterial;
    ['Material.012']: THREE.MeshStandardMaterial;
    ['매테리얼.022']: THREE.MeshStandardMaterial;
  };
};

export function SquareMap(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.square_map_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tree1.geometry}
        material={materials['Material.021']}
        position={[12.6, 0.95, -13.38]}
        rotation={[0, 0.01, 0]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.tree1001.geometry}
        material={materials['Material.021']}
        position={[15.11, 0.95, -12.78]}
        rotation={[Math.PI, -0.02, Math.PI]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.tree1002.geometry}
        material={materials['Material.021']}
        position={[11.5, 0.95, -10.12]}
        rotation={[0, -1.24, 0]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.tree1003.geometry}
        material={materials['Material.021']}
        position={[16.27, 0.79, -15.64]}
        rotation={[2.85, 0.95, -2.93]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.tree1004.geometry}
        material={materials['Material.021']}
        position={[13.68, 0.94, -9.98]}
        rotation={[-2.95, 1.21, 3.06]}
        scale={0.15}
      />
      <group
        position={[-9.78, 4.51, 8.01]}
        rotation={[0, 0.88, 0]}
        scale={0.04}
      >
        <mesh
          geometry={nodes.Sphere003.geometry}
          material={materials['Material.037']}
        />
        <mesh
          geometry={nodes.Sphere003_1.geometry}
          material={materials['Material.038']}
        />
        <mesh
          geometry={nodes.Sphere003_2.geometry}
          material={materials['Material.039']}
        />
        <mesh
          geometry={nodes.Sphere003_3.geometry}
          material={materials['Material.040']}
        />
        <mesh
          geometry={nodes.Sphere003_4.geometry}
          material={materials['Material.041']}
        />
        <mesh
          geometry={nodes.Sphere003_5.geometry}
          material={materials['Material.042']}
        />
        <mesh
          geometry={nodes.Sphere003_6.geometry}
          material={materials['Material.043']}
        />
      </group>
      <group
        position={[3.17, 1.99, 5.94]}
        rotation={[0, -1.07, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Sphere001.geometry}
          material={materials['Material.044']}
        />
        <mesh
          geometry={nodes.Sphere001_1.geometry}
          material={materials['Material.045']}
        />
        <mesh
          geometry={nodes.Sphere001_2.geometry}
          material={materials['Material.046']}
        />
        <mesh
          geometry={nodes.Sphere001_3.geometry}
          material={materials['Material.047']}
        />
        <mesh
          geometry={nodes.Sphere001_4.geometry}
          material={materials['Material.048']}
        />
        <mesh
          geometry={nodes.Sphere001_5.geometry}
          material={materials['Material.049']}
        />
        <mesh
          geometry={nodes.Sphere001_6.geometry}
          material={materials['Material.050']}
        />
      </group>
      <group
        position={[-11.71, 3.31, -9.7]}
        rotation={[-0.07, 0.89, 0.24]}
        scale={0.17}
      >
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials['매테리얼.020']}
        />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials['매테리얼.021']}
        />
        <mesh
          geometry={nodes.Cube003_2.geometry}
          material={materials['Material.051']}
        />
        <mesh
          geometry={nodes.Cube003_3.geometry}
          material={materials['Material.052']}
        />
        <mesh
          geometry={nodes.Cube003_4.geometry}
          material={materials['Material.053']}
        />
        <mesh
          geometry={nodes.Cube003_5.geometry}
          material={materials['Material.054']}
        />
        <mesh
          geometry={nodes.Cube003_6.geometry}
          material={materials['Material.055']}
        />
        <mesh
          geometry={nodes.Cube003_7.geometry}
          material={materials['Material.056']}
        />
      </group>
      <group
        position={[1.87, 1.95, 6.92]}
        rotation={[-Math.PI, 0.97, -3.01]}
        scale={0.16}
      >
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials['Material.074']}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials['Material.075']}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials['Material.076']}
        />
        <mesh
          geometry={nodes.Cube002_3.geometry}
          material={materials['Material.077']}
        />
        <mesh
          geometry={nodes.Cube002_4.geometry}
          material={materials['Material.078']}
        />
        <mesh
          geometry={nodes.Cube002_5.geometry}
          material={materials['Material.079']}
        />
      </group>
      <group position={[4.36, 1.43, 13.05]} scale={0.01}>
        <mesh
          geometry={nodes.Sphere008.geometry}
          material={materials['Material.080']}
        />
        <mesh
          geometry={nodes.Sphere008_1.geometry}
          material={materials['Material.081']}
        />
        <mesh
          geometry={nodes.Sphere008_2.geometry}
          material={materials['Material.082']}
        />
        <mesh
          geometry={nodes.Sphere008_3.geometry}
          material={materials['Material.083']}
        />
        <mesh
          geometry={nodes.Sphere008_4.geometry}
          material={materials['Material.084']}
        />
        <mesh
          geometry={nodes.Sphere008_5.geometry}
          material={materials['Material.085']}
        />
        <mesh
          geometry={nodes.Sphere008_6.geometry}
          material={materials['Material.086']}
        />
      </group>
      <group
        position={[-15.1, 1.53, 1.53]}
        rotation={[0, 0.16, 0]}
        scale={0.11}
      >
        <mesh
          geometry={nodes.Mesh1749.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Mesh1749_1.geometry}
          material={materials['매테리얼.026']}
        />
      </group>
      <group
        position={[-15.1, 1.53, 5.68]}
        rotation={[-Math.PI, 0.92, -Math.PI]}
        scale={0.11}
      >
        <mesh
          geometry={nodes.Mesh002.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Mesh002_1.geometry}
          material={materials['매테리얼.026']}
        />
      </group>
      <group
        position={[-15.1, 1.53, 10.35]}
        rotation={[Math.PI, -0.74, Math.PI]}
        scale={0.11}
      >
        <mesh
          geometry={nodes.Mesh025.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Mesh025_1.geometry}
          material={materials['매테리얼.026']}
        />
      </group>
      <group
        position={[-15.1, 1.53, 15.21]}
        rotation={[-Math.PI, 1.07, -Math.PI]}
        scale={0.11}
      >
        <mesh
          geometry={nodes.Mesh026.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Mesh026_1.geometry}
          material={materials['매테리얼.026']}
        />
      </group>
      <group position={[-17.38, 1.85, 3.55]} scale={0.12}>
        <mesh
          geometry={nodes.Mesh029.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Mesh029_1.geometry}
          material={materials['매테리얼.027']}
        />
      </group>
      <group
        position={[-17.38, 1.85, 7.86]}
        rotation={[0, -0.89, 0]}
        scale={0.12}
      >
        <mesh
          geometry={nodes.Mesh091.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Mesh091_1.geometry}
          material={materials['매테리얼.027']}
        />
      </group>
      <group
        position={[-17.38, 1.85, 12.72]}
        rotation={[0, 1.28, 0]}
        scale={0.12}
      >
        <mesh
          geometry={nodes.Mesh092.geometry}
          material={materials['Material.001']}
        />
        <mesh
          geometry={nodes.Mesh092_1.geometry}
          material={materials['매테리얼.027']}
        />
      </group>
      <group
        position={[0, -2, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[18, 2, 18]}
      >
        <mesh
          geometry={nodes.큐브_1.geometry}
          material={materials['매테리얼.017']}
        />
        <mesh
          geometry={nodes.큐브_2.geometry}
          material={materials['매테리얼.018']}
        />
        <mesh
          geometry={nodes.큐브_3.geometry}
          material={materials['매테리얼.019']}
        />
      </group>
      <mesh
        geometry={nodes.큐브001.geometry}
        material={materials.매테리얼}
        position={[0, -6.39, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[18, 2, 18]}
      />
      <mesh
        geometry={nodes.실린더003.geometry}
        material={materials['매테리얼.013']}
        position={[-1.56, 1.86, 0.01]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.09, -0.9, -0.09]}
      />
      <mesh
        geometry={nodes.큐브002.geometry}
        material={materials['매테리얼.017']}
        position={[0, -2, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[18, 2, 18]}
      />
      <mesh
        geometry={nodes.실린더.geometry}
        material={materials['매테리얼.013']}
        position={[-1.56, 0.86, -3.63]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.09, -0.9, -0.09]}
      />
      <mesh
        geometry={nodes.실린더001.geometry}
        material={materials['매테리얼.013']}
        position={[-1.56, 1.14, -2.32]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.09, -0.9, -0.09]}
      />
      <mesh
        geometry={nodes.실린더002.geometry}
        material={materials['매테리얼.013']}
        position={[-1.56, 1.64, -1.05]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.09, -0.9, -0.09]}
      />
      <mesh
        geometry={nodes.평면.geometry}
        material={materials['매테리얼.008']}
        position={[0, -0.46, 0]}
        scale={[1.79, 1, 3.94]}
      />
      <mesh
        geometry={nodes.평면001.geometry}
        material={materials['매테리얼.003']}
        position={[0, -0.39, 0]}
        scale={[1.79, 1, 3.94]}
      />
      <group position={[0.07, 7.46, -11.18]} scale={7.16}>
        <mesh
          geometry={nodes.원형_1.geometry}
          material={materials['매테리얼.014']}
        />
        <mesh
          geometry={nodes.원형_2.geometry}
          material={materials['매테리얼.016']}
        />
      </group>
      <mesh
        geometry={nodes.fantasy_plant053.geometry}
        material={materials['Material.002']}
        position={[1.04, 1.2, -7.08]}
        rotation={[0, -0.99, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.stone020.geometry}
        material={materials['Material.004']}
        position={[4.43, 0.84, -10.69]}
        scale={0.45}
      />
      <mesh
        geometry={nodes.stone001.geometry}
        material={materials['Material.004']}
        position={[-4.79, 0.92, -10.69]}
        rotation={[-Math.PI, 0.31, -Math.PI]}
        scale={0.45}
      />
      <mesh
        geometry={nodes.building015.geometry}
        material={materials['Material.005']}
        position={[-9.8, 1.8, 10.99]}
        scale={0.35}
      />
      <mesh
        geometry={nodes.building012.geometry}
        material={materials['Material.006']}
        position={[10.98, 2.37, 7.68]}
        rotation={[0, -1.57, 0]}
        scale={0.61}
      />
      <mesh
        geometry={nodes.building011.geometry}
        material={materials['Material.007']}
        position={[9.94, 1.3, 14.82]}
        rotation={[0, -1.57, 0]}
        scale={0.63}
      />
      <mesh
        geometry={nodes.prop032.geometry}
        material={materials['Material.008']}
        position={[12.45, 0.41, 4.9]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.prop006.geometry}
        material={materials['Material.009']}
        position={[9.85, 0.52, 5.05]}
        rotation={[0, -1.57, 0]}
        scale={0.47}
      />
      <mesh
        geometry={nodes.fantasy_plant190.geometry}
        material={materials['Material.010']}
        position={[-16.4, 0.82, -15.86]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.fantasy_plant003.geometry}
        material={materials['Material.010']}
        position={[-11.91, 0.82, -16.02]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.fantasy_plant004.geometry}
        material={materials['Material.010']}
        position={[-14.66, 0.82, -10.49]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.fantasy_plant127.geometry}
        material={materials['Material.011']}
        position={[-14.11, 0.82, -15.19]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.fantasy_plant005.geometry}
        material={materials['Material.011']}
        position={[-12.72, 0.82, -10.59]}
        rotation={[-Math.PI, 0.68, -Math.PI]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.fantasy_plant117.geometry}
        material={materials['Material.013']}
        position={[-16.58, 0.82, -14.09]}
        rotation={[0, 0, 0.24]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.fantasy_plant006.geometry}
        material={materials['Material.013']}
        position={[-11.2, 0.8, -13.94]}
        rotation={[0, 0, -0.11]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.fantasy_plant007.geometry}
        material={materials['Material.013']}
        position={[-14.58, 0.7, -17.11]}
        rotation={[-0.11, 0.01, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.mushroom004.geometry}
        material={materials['Material.014']}
        position={[-10.52, 0.73, -11.21]}
        rotation={[0, 0, -0.11]}
        scale={0.24}
      />
      <mesh
        geometry={nodes.mushroom001.geometry}
        material={materials['Material.014']}
        position={[-16.91, 0.79, -11.24]}
        rotation={[3.12, -0.18, 3.03]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.mushroom010.geometry}
        material={materials['Material.015']}
        position={[-14.18, 4.01, -12.94]}
        scale={0.24}
      />
      <mesh
        geometry={nodes.prop054.geometry}
        material={materials['Material.016']}
        position={[14.28, 0.39, 7.22]}
        rotation={[0, 1.57, 0]}
        scale={0.34}
      />
      <mesh
        geometry={nodes.prop053.geometry}
        material={materials['Material.017']}
        position={[12.88, 0.25, 8.5]}
        scale={0.35}
      />
      <mesh
        geometry={nodes.prop001.geometry}
        material={materials['Material.017']}
        position={[13.53, 0.25, 8.5]}
        scale={0.35}
      />
      <mesh
        geometry={nodes.fantasy_plant020.geometry}
        material={materials['Material.018']}
        position={[14, 0.87, 13]}
        scale={0.21}
      />
      <mesh
        geometry={nodes.fantasy_plant008.geometry}
        material={materials['Material.018']}
        position={[16.8, 1, 10.7]}
        rotation={[0, -0.67, 0]}
        scale={0.23}
      />
      <mesh
        geometry={nodes.fantasy_plant009.geometry}
        material={materials['Material.018']}
        position={[14.68, 0.9, 6.29]}
        scale={0.21}
      />
      <mesh
        geometry={nodes.fantasy_plant010.geometry}
        material={materials['Material.018']}
        position={[16.9, 0.9, 2.49]}
        scale={0.21}
      />
      <mesh
        geometry={nodes.fantasy_plant011.geometry}
        material={materials['Material.018']}
        position={[16.8, 0.65, 14.81]}
        rotation={[0, 1.39, 0]}
        scale={0.15}
      />
      <mesh
        geometry={nodes.prop046.geometry}
        material={materials['Material.019']}
        position={[9.54, 0.57, 10.66]}
        rotation={[0, -1.57, 0]}
        scale={0.31}
      />
      <mesh
        geometry={nodes.mushroom076.geometry}
        material={materials['Material.022']}
        position={[-16.24, 1.22, -9.9]}
        rotation={[0.11, -0.19, 0]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.mushroom002.geometry}
        material={materials['Material.022']}
        position={[-13.59, 1.07, -10.86]}
        rotation={[0.27, -1.17, 0.23]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.mushroom003.geometry}
        material={materials['Material.022']}
        position={[-11.01, 1.07, -15.47]}
        rotation={[2.96, -0.96, 2.97]}
        scale={0.04}
      />
      <mesh
        geometry={nodes.fantasy_plant503.geometry}
        material={materials['Material.023']}
        position={[14.72, 0.8, -8.78]}
        rotation={[0.12, 0, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.fantasy_plant015.geometry}
        material={materials['Material.023']}
        position={[12.54, 0.95, -12.69]}
        rotation={[0, -1.46, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.fantasy_plant016.geometry}
        material={materials['Material.023']}
        position={[12.56, 0.92, -15.52]}
        rotation={[3.02, -1.34, Math.PI]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.fantasy_plant017.geometry}
        material={materials['Material.023']}
        position={[9.9, 0.76, -12.64]}
        rotation={[1.4, -1.31, 1.41]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.fantasy_plant023.geometry}
        material={materials['Material.025']}
        position={[-15.27, 1.88, 12.59]}
        scale={0.54}
      />
      <mesh
        geometry={nodes.fantasy_plant024.geometry}
        material={materials['Material.025']}
        position={[-15.27, 1.86, 7.75]}
        scale={0.54}
      />
      <mesh
        geometry={nodes.fantasy_plant025.geometry}
        material={materials['Material.025']}
        position={[-15.27, 1.86, 3.63]}
        scale={0.54}
      />
      <mesh
        geometry={nodes.fantasy_plant026.geometry}
        material={materials['Material.026']}
        position={[-17.52, 1.73, 15.25]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.fantasy_plant027.geometry}
        material={materials['Material.026']}
        position={[-17.52, 1.73, 10.29]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.fantasy_plant028.geometry}
        material={materials['Material.026']}
        position={[-17.52, 1.73, 5.7]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.fantasy_plant029.geometry}
        material={materials['Material.026']}
        position={[-17.52, 1.73, 1.16]}
        scale={0.5}
      />
      <mesh
        geometry={nodes.stone003.geometry}
        material={materials['Material.028']}
        position={[-8.5, -0.01, 15.1]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone002.geometry}
        material={materials['Material.028']}
        position={[-7.93, -0.01, 14.45]}
        rotation={[0, -1.48, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone004.geometry}
        material={materials['Material.028']}
        position={[-8.46, -0.01, 14.45]}
        rotation={[Math.PI, -0.04, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone005.geometry}
        material={materials['Material.028']}
        position={[-8.11, -0.01, 14.91]}
        rotation={[Math.PI, -0.04, Math.PI]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.stone006.geometry}
        material={materials['Material.029']}
        position={[-7.73, -0.01, 15.1]}
        rotation={[0, -0.38, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone007.geometry}
        material={materials['Material.029']}
        position={[-8.14, -0.01, 15.51]}
        rotation={[Math.PI, -1.14, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone008.geometry}
        material={materials['Material.028']}
        position={[6.77, -0.01, 14.32]}
        rotation={[Math.PI, -1.53, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone009.geometry}
        material={materials['Material.028']}
        position={[7.4, -0.01, 14.93]}
        rotation={[Math.PI, -0.05, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone010.geometry}
        material={materials['Material.028']}
        position={[7.42, -0.01, 14.39]}
        rotation={[0, 1.56, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone011.geometry}
        material={materials['Material.028']}
        position={[6.94, -0.01, 14.73]}
        rotation={[0, 1.56, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.stone012.geometry}
        material={materials['Material.029']}
        position={[6.74, -0.01, 15.1]}
        rotation={[Math.PI, -1.14, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone013.geometry}
        material={materials['Material.029']}
        position={[6.34, -0.01, 14.67]}
        rotation={[-Math.PI, 0.48, -Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone014.geometry}
        material={materials['Material.028']}
        position={[6.28, -0.01, 7.57]}
        rotation={[0, -1.07, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone015.geometry}
        material={materials['Material.028']}
        position={[7.13, -0.01, 7.77]}
        rotation={[Math.PI, -0.59, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone016.geometry}
        material={materials['Material.028']}
        position={[6.88, -0.01, 7.3]}
        rotation={[-Math.PI, 1.03, -Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone017.geometry}
        material={materials['Material.028']}
        position={[6.64, -0.01, 7.84]}
        rotation={[-Math.PI, 1.03, -Math.PI]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.stone018.geometry}
        material={materials['Material.029']}
        position={[6.66, -0.01, 8.26]}
        rotation={[0, -1.46, 0]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone019.geometry}
        material={materials['Material.029']}
        position={[6.09, -0.01, 8.1]}
        rotation={[Math.PI, -0.07, Math.PI]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.stone024.geometry}
        material={materials['Material.030']}
        position={[3.09, 0.64, 5.48]}
        scale={0.22}
      />
      <mesh
        geometry={nodes.tree037.geometry}
        material={materials['Material.035']}
        position={[4.16, 0.85, -8.08]}
        scale={0.48}
      />
      <mesh
        geometry={nodes.tree001.geometry}
        material={materials['Material.035']}
        position={[-0.54, 0.85, -6.37]}
        rotation={[0, -1.15, 0]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.tree002.geometry}
        material={materials['Material.035']}
        position={[-5.79, 0.05, 9.15]}
        scale={0.48}
      />
      <mesh
        geometry={nodes.tree003.geometry}
        material={materials['Material.035']}
        position={[-3.14, 0.2, 4.67]}
        rotation={[0, -0.82, 0]}
        scale={0.48}
      />
      <mesh
        geometry={nodes.stone023.geometry}
        material={materials['Material.036']}
        position={[-10.85, 1.13, 17.07]}
        scale={0.21}
      />
      <mesh
        geometry={nodes.fantasy_plant047.geometry}
        material={materials['Material.057']}
        position={[-4.59, 1, -8.81]}
        scale={0.54}
      />
      <mesh
        geometry={nodes.fantasy_plant032.geometry}
        material={materials['Material.058']}
        position={[9.63, 0.13, 11.78]}
        scale={0.39}
      />
      <mesh
        geometry={nodes.fantasy_plant033.geometry}
        material={materials['Material.059']}
        position={[9.46, 0.18, 12.47]}
        scale={0.39}
      />
      <mesh
        geometry={nodes.tree005.geometry}
        material={materials['Material.060']}
        position={[2.11, 0.2, 10.17]}
        scale={0.66}
      />
      <mesh
        geometry={nodes.tree004.geometry}
        material={materials['Material.060']}
        position={[8.56, 0.22, 17.05]}
        rotation={[0, -1.41, 0]}
        scale={0.43}
      />
      <mesh
        geometry={nodes.fantasy_plant034.geometry}
        material={materials['Material.064']}
        position={[-592.04, 1.24, 122.42]}
      />
      <mesh
        geometry={nodes.fantasy_plant035.geometry}
        material={materials['Material.065']}
        position={[-5.67, 0.43, 6.33]}
        rotation={[0, 1.07, 0]}
        scale={0.16}
      />
      <mesh
        geometry={nodes.fantasy_plant036.geometry}
        material={materials['Material.065']}
        position={[-5.72, 0.5, 7.82]}
        rotation={[0, 1.07, 0]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant038.geometry}
        material={materials['Material.065']}
        position={[-6.64, 0.5, 7.82]}
        rotation={[0, 1.07, 0]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant039.geometry}
        material={materials['Material.065']}
        position={[-6.64, 0.71, 7.01]}
        rotation={[0, 1.31, 0]}
        scale={0.26}
      />
      <mesh
        geometry={nodes.fantasy_plant040.geometry}
        material={materials['Material.065']}
        position={[-6.64, 0.5, 6.08]}
        rotation={[0, 1.07, 0]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant041.geometry}
        material={materials['Material.065']}
        position={[-5.45, 0.5, 7.18]}
        rotation={[0, 1.55, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant054.geometry}
        material={materials['Material.067']}
        position={[2.53, 0.3, 16.52]}
        rotation={[0, -0.15, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant042.geometry}
        material={materials['Material.067']}
        position={[3.37, 0.3, 16.37]}
        rotation={[0, -1.02, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant043.geometry}
        material={materials['Material.067']}
        position={[3.21, 0.3, 17.48]}
        rotation={[0, 0.79, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant044.geometry}
        material={materials['Material.067']}
        position={[4.21, 0.3, 16.19]}
        rotation={[0, 0.92, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant045.geometry}
        material={materials['Material.067']}
        position={[4.05, 0.3, 17.03]}
        rotation={[0, 1.47, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant046.geometry}
        material={materials['Material.067']}
        position={[2.4, 0.3, 17.39]}
        rotation={[0, 0.03, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.prop062.geometry}
        material={materials['Material.068']}
        position={[5.22, 0.94, 11.26]}
        scale={0.55}
      />
      <mesh
        geometry={nodes.prop073.geometry}
        material={materials['Material.069']}
        position={[4.4, 0.5, 12.72]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.57}
      />
      <mesh
        geometry={nodes.prop002.geometry}
        material={materials['Material.069']}
        position={[5.64, 0.5, 12.72]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.57}
      />
      <mesh
        geometry={nodes.prop003.geometry}
        material={materials['Material.069']}
        position={[4.4, 0.5, 9.77]}
        rotation={[0, 1.1, 0]}
        scale={0.57}
      />
      <mesh
        geometry={nodes.prop004.geometry}
        material={materials['Material.069']}
        position={[6.78, 0.32, 10]}
        rotation={[0.01, -0.84, -1.56]}
        scale={0.57}
      />
      <mesh
        geometry={nodes.prop074.geometry}
        material={materials['Material.070']}
        position={[-1.82, 1.46, 4.97]}
        rotation={[0, -0.84, 0]}
        scale={0.57}
      />
      <mesh
        geometry={nodes.prop017.geometry}
        material={materials['Material.071']}
        position={[-8.79, 0.29, 9.9]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.prop005.geometry}
        material={materials['Material.071']}
        position={[-8.79, 0.29, 10.6]}
        rotation={[0, -0.6, 0]}
        scale={0.4}
      />
      <mesh
        geometry={nodes.building001.geometry}
        material={materials['Material.072']}
        position={[-2.44, 0.49, 12.92]}
        rotation={[0, -1.57, 0]}
        scale={0.39}
      />
      <mesh
        geometry={nodes.prop064.geometry}
        material={materials['Material.073']}
        position={[-1.69, 0.95, 16.7]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.55}
      />
      <mesh
        geometry={nodes.prop007.geometry}
        material={materials['Material.073']}
        position={[1.88, 0.93, 13.45]}
        scale={0.55}
      />
      <mesh
        geometry={nodes.prop008.geometry}
        material={materials['Material.073']}
        position={[1.88, 0.93, 6.93]}
        scale={0.55}
      />
      <mesh
        geometry={nodes.fantasy_plant001.geometry}
        material={materials['Material.002']}
        position={[-1.74, 1.2, -7.08]}
        rotation={[Math.PI, -1.22, Math.PI]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant002.geometry}
        material={materials['Material.002']}
        position={[5.08, 1.12, -9.87]}
        rotation={[0, -0.33, 0]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.fantasy_plant048.geometry}
        material={materials['Material.057']}
        position={[2.48, 0.98, -7.05]}
        rotation={[0, 1.02, 0]}
        scale={0.54}
      />
      <mesh
        geometry={nodes.fantasy_plant049.geometry}
        material={materials['Material.057']}
        position={[4.96, 1.14, -13.12]}
        rotation={[0, 1.47, 0]}
        scale={0.89}
      />
      <mesh
        geometry={nodes.fantasy_plant037.geometry}
        material={materials['Material.087']}
        position={[-578.06, 3.93, 115.18]}
      />
      <mesh
        geometry={nodes.animal006.geometry}
        material={materials['Material.088']}
        position={[-12.56, 1.49, -2.25]}
        rotation={[0, 0.61, 0]}
        scale={0.62}
      />
      <mesh
        geometry={nodes.animal001.geometry}
        material={materials['Material.089']}
        position={[8.07, 2.11, -2.53]}
        rotation={[0, -0.52, 0]}
        scale={0.61}
      />
      <mesh
        geometry={nodes.animal009.geometry}
        material={materials['Material.090']}
        position={[-7.46, 2.38, -7.8]}
        rotation={[-Math.PI, 1.43, -Math.PI]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.animal011.geometry}
        material={materials['Material.091']}
        position={[14.11, 1.68, -2.2]}
        rotation={[0, 0.84, 0]}
        scale={0.46}
      />
      <mesh
        geometry={nodes.fantasy_plant075.geometry}
        material={materials['Material.092']}
        position={[-9.47, 0.26, -4.18]}
        scale={0.24}
      />
      <mesh
        geometry={nodes.fantasy_plant050.geometry}
        material={materials['Material.092']}
        position={[-16.31, 0.6, -7.69]}
        rotation={[0.22, 0, 0]}
        scale={0.24}
      />
      <mesh
        geometry={nodes.fantasy_plant051.geometry}
        material={materials['Material.092']}
        position={[-6.14, 0.26, -2.27]}
        rotation={[0, -1.51, 0]}
        scale={0.26}
      />
      <mesh
        geometry={nodes.fantasy_plant071.geometry}
        material={materials['Material.093']}
        position={[5.61, 0.32, -4.34]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.fantasy_plant052.geometry}
        material={materials['Material.093']}
        position={[16.11, 0.29, -1.82]}
        rotation={[0.13, -1.15, 0.12]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.fantasy_plant055.geometry}
        material={materials['Material.093']}
        position={[11.53, 0.36, -5.63]}
        rotation={[0.05, -1.15, 0.03]}
        scale={0.26}
      />
      <group position={[16.91, 2.09, 5.44]} scale={0.08}>
        <mesh
          geometry={nodes.Mesh093.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh093_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh093_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <group
        position={[16.91, 2.09, 8.62]}
        rotation={[0, -0.69, 0]}
        scale={0.08}
      >
        <mesh
          geometry={nodes.Mesh099.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh099_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh099_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <group
        position={[16.4, 2.17, 12.39]}
        rotation={[0, -1.17, 0]}
        scale={0.09}
      >
        <mesh
          geometry={nodes.Mesh100.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh100_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh100_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <group
        position={[15.7, 2.52, 10.27]}
        rotation={[Math.PI, -1.52, Math.PI]}
        scale={0.1}
      >
        <mesh
          geometry={nodes.Mesh101.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh101_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh101_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <group
        position={[16.4, 1.93, 16.39]}
        rotation={[Math.PI, -0.99, Math.PI]}
        scale={0.08}
      >
        <mesh
          geometry={nodes.Mesh102.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh102_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh102_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <group
        position={[15.32, 1.93, 14.66]}
        rotation={[Math.PI, -0.6, Math.PI]}
        scale={0.09}
      >
        <mesh
          geometry={nodes.Mesh103.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh103_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh103_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <group position={[16.5, 1.74, 3.5]} rotation={[0, 0.81, 0]} scale={0.07}>
        <mesh
          geometry={nodes.Mesh104.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh104_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh104_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <group
        position={[15.7, 2.09, 7.01]}
        rotation={[0, -0.75, 0]}
        scale={0.08}
      >
        <mesh
          geometry={nodes.Mesh105.geometry}
          material={materials['매테리얼.028']}
        />
        <mesh
          geometry={nodes.Mesh105_1.geometry}
          material={materials['Material.031']}
        />
        <mesh
          geometry={nodes.Mesh105_2.geometry}
          material={materials['매테리얼.029']}
        />
      </group>
      <mesh
        geometry={nodes.fantasy_plant061.geometry}
        material={materials['Material.012']}
        position={[15.04, 2.27, -11.02]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant062.geometry}
        material={materials['매테리얼.022']}
        position={[15.04, 2.27, -11.02]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant063.geometry}
        material={materials['Material.012']}
        position={[15.04, 2.34, -14.56]}
        rotation={[0, 1.1, 0]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant064.geometry}
        material={materials['매테리얼.022']}
        position={[15.04, 2.34, -14.56]}
        rotation={[0, 1.1, 0]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant065.geometry}
        material={materials['Material.012']}
        position={[10.6, 1.9, -11.42]}
        rotation={[-0.1, 0.82, 0.14]}
        scale={0.14}
      />
      <mesh
        geometry={nodes.fantasy_plant066.geometry}
        material={materials['매테리얼.022']}
        position={[10.6, 1.9, -11.42]}
        rotation={[-0.1, 0.82, 0.14]}
        scale={0.14}
      />
      <mesh
        geometry={nodes.fantasy_plant067.geometry}
        material={materials['Material.012']}
        position={[12.94, 2.36, -11.42]}
        rotation={[-0.09, 1.21, 0.14]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.fantasy_plant068.geometry}
        material={materials['매테리얼.022']}
        position={[12.94, 2.36, -11.42]}
        rotation={[-0.09, 1.21, 0.14]}
        scale={0.19}
      />
    </group>
  );
}

useGLTF.preload(glbs.square_map_glb);
