/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tile.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    평면001: THREE.Mesh;
  };
  materials: {
    매테리얼: THREE.MeshStandardMaterial;
  };
};

export function Tile(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.tile_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.평면001.geometry}
        material={materials.매테리얼}
        scale={[2, 1, 2]}
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload(glbs.tile_glb);
