/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 game1Map.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    큐브_1: THREE.Mesh;
    큐브_2: THREE.Mesh;
    큐브_3: THREE.Mesh;
    fence_main_mat_0002: THREE.Mesh;
    fence_main_mat_0010: THREE.Mesh;
  };
  materials: {
    매테리얼: THREE.MeshStandardMaterial;
    ['매테리얼.001']: THREE.MeshStandardMaterial;
    ['매테리얼.002']: THREE.MeshStandardMaterial;
    main_mat: THREE.MeshStandardMaterial;
  };
};

export function Game1Map(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.game_1_map_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[96, -1, 0]} scale={[100.5, 1, 4]}>
        <mesh
          geometry={nodes.큐브_1.geometry}
          material={materials.매테리얼}
          receiveShadow
        />
        <mesh
          geometry={nodes.큐브_2.geometry}
          material={materials['매테리얼.001']}
          receiveShadow
        />
        <mesh
          geometry={nodes.큐브_3.geometry}
          material={materials['매테리얼.002']}
          receiveShadow
        />
      </group>
      <mesh
        geometry={nodes.fence_main_mat_0002.geometry}
        material={materials.main_mat}
        position={[28.91, -0.3, -10.18]}
        rotation={[0, 1.57, 0]}
      />
      <mesh
        geometry={nodes.fence_main_mat_0010.geometry}
        material={materials.main_mat}
        position={[-3.44, 0.7, 0.09]}
        rotation={[Math.PI, 0, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload(glbs.game_1_map_glb);
