/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rock4.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    mountain005: THREE.Mesh;
  };
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export function Rock4(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.rock_4_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mountain005.geometry}
        material={materials['Material.001']}
        position={[0, 6.15, 0]}
        scale={0.64}
      />
    </group>
  );
}

// useGLTF.preload(glbs.rock_4_glb);
