/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rock5.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    mountain006: THREE.Mesh;
  };
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial;
  };
};

export function Rock5(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.rock_5_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mountain006.geometry}
        material={materials['Material.005']}
        position={[0, 6.44, 0]}
        scale={0.58}
      />
    </group>
  );
}

// useGLTF.preload(glbs.rock_5_glb);
