/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rock2.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    mountain002: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
  };
};

export function Rock2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.rock_2_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mountain002.geometry}
        material={materials['Material.002']}
        position={[0, 6.29, 0]}
        scale={0.58}
      />
    </group>
  );
}

useGLTF.preload(glbs.rock_2_glb);
