/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rock1.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    mountain001: THREE.Mesh;
  };
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial;
  };
};

export function Rock1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.rock_1_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mountain001.geometry}
        material={materials['Material.004']}
        position={[0, 4.86, 0]}
        scale={0.52}
      />
    </group>
  );
}

// useGLTF.preload(glbs.rock_1_glb);
