/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rock3.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    mountain003: THREE.Mesh;
  };
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial;
  };
};

export function Rock3(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.rock_3_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mountain003.geometry}
        material={materials['Material.003']}
        position={[0, 5.44, 0]}
        scale={0.58}
      />
    </group>
  );
}

useGLTF.preload(glbs.rock_3_glb);
