/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Tree4.glb -t
*/

import * as THREE from 'three';
import React, { useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';
import { useFrame } from '@react-three/fiber';

type GLTFResult = GLTF & {
  nodes: {
    tree4: THREE.Mesh;
  };
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial;
  };
};

export function Tree4(props: JSX.IntrinsicElements['group']) {
  const [angle, setAngle] = useState(0);
  useFrame(() => {
    setAngle((prev) => prev + 1);
  });
  const { nodes, materials } = useGLTF(glbs.tree_4_glb) as GLTFResult;
  return (
    <group {...props} dispose={null} rotation={[0, (Math.PI / 360) * angle, 0]}>
      <mesh
        geometry={nodes.tree4.geometry}
        material={materials['Material.005']}
        position={[0, 2.57, 0]}
        scale={0.2}
      />
    </group>
  );
}

useGLTF.preload(glbs.tree_4_glb);
