/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Sprout.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    sprout: THREE.Mesh;
  };
  materials: {
    매테리얼: THREE.MeshStandardMaterial;
  };
};

export function Sprout(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.sprout_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.sprout.geometry}
        material={materials.매테리얼}
        position={[0, 0.17, -0.05]}
        rotation={[-Math.PI, -1.37, 3]}
        scale={[0.05, 0.03, 0.02]}
      />
    </group>
  );
}

useGLTF.preload(glbs.sprout_glb);
