/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Tree6.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    tree6: THREE.Mesh;
  };
  materials: {
    ['Material.012']: THREE.MeshStandardMaterial;
  };
};

export function Tree6(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.tree_6_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.tree6.geometry}
        material={materials['Material.012']}
        position={[0.04, 2.02, 0]}
        scale={0.17}
        castShadow
      />
    </group>
  );
}

// useGLTF.preload(glbs.tree_6_glb);
