/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tFlower_1.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    fantasy_plant001: THREE.Mesh;
    fantasy_plant053: THREE.Mesh;
    fantasy_plant004: THREE.Mesh;
    fantasy_plant005: THREE.Mesh;
    tree001: THREE.Mesh;
    tree002: THREE.Mesh;
    tree003: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
  };
};

export function TFlower_1(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.t_flower_1_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.fantasy_plant001.geometry}
        material={materials['Material.002']}
        position={[1.45, 0.38, -0.03]}
        rotation={[0, -0.77, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.fantasy_plant053.geometry}
        material={materials['Material.002']}
        position={[-1.42, 0.5, 1.64]}
        rotation={[0, 1.24, 0]}
        scale={0.13}
      />
      <mesh
        geometry={nodes.fantasy_plant004.geometry}
        material={materials['Material.002']}
        position={[-0.96, 0.42, -1.37]}
        rotation={[0, -0.72, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.fantasy_plant005.geometry}
        material={materials['Material.002']}
        position={[-0.95, 0.35, 1.54]}
        rotation={[0, 0.12, 0]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.tree001.geometry}
        material={materials['Material.009']}
        position={[1.72, 0.18, 0.36]}
        rotation={[0, 1.46, 0]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.tree002.geometry}
        material={materials['Material.009']}
        position={[1.62, 0.18, -0.53]}
        rotation={[-Math.PI, 0.54, -Math.PI]}
        scale={0.32}
      />
      <mesh
        geometry={nodes.tree003.geometry}
        material={materials['Material.009']}
        position={[-1.61, 0.15, 0.98]}
        rotation={[0, 0.54, 0]}
        scale={0.3}
      />
    </group>
  );
}

useGLTF.preload(glbs.t_flower_1_glb);
