/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tFlower_2.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    fantasy_plant002: THREE.Mesh;
    fantasy_plant003: THREE.Mesh;
    fantasy_plant076: THREE.Mesh;
    tree004: THREE.Mesh;
    tree005: THREE.Mesh;
    tree006: THREE.Mesh;
    tree007: THREE.Mesh;
    fantasy_plant006: THREE.Mesh;
    fantasy_plant007: THREE.Mesh;
    fantasy_plant008: THREE.Mesh;
    tree010: THREE.Mesh;
    tree011: THREE.Mesh;
    tree012: THREE.Mesh;
    tree013: THREE.Mesh;
  };
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
    ['Material.005']: THREE.MeshStandardMaterial;
  };
};

export function TFlower_2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.t_flower_2_glb) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.fantasy_plant002.geometry}
        material={materials['Material.003']}
        position={[1.76, 0.3, 0.97]}
        rotation={[0, 1.05, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.fantasy_plant003.geometry}
        material={materials['Material.003']}
        position={[-1.27, 0.3, -1.44]}
        rotation={[0, -1.44, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.fantasy_plant076.geometry}
        material={materials['Material.003']}
        position={[-1.43, 0.3, 1.46]}
        rotation={[0, -0.46, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.tree004.geometry}
        material={materials['Material.001']}
        position={[1.46, 0.22, -1.14]}
        rotation={[-Math.PI, 0.81, -Math.PI]}
        scale={0.25}
      />
      <mesh
        geometry={nodes.tree005.geometry}
        material={materials['Material.001']}
        position={[-1.52, 0.22, -0.02]}
        rotation={[0, -1.04, 0]}
        scale={0.25}
      />
      <mesh
        geometry={nodes.tree006.geometry}
        material={materials['Material.005']}
        position={[1.09, 0.15, 1.47]}
        scale={0.27}
      />
      <mesh
        geometry={nodes.tree007.geometry}
        material={materials['Material.005']}
        position={[-0.18, 0.15, -1.61]}
        rotation={[0, -0.56, 0]}
        scale={0.27}
      />
      <mesh
        geometry={nodes.fantasy_plant006.geometry}
        material={materials['Material.003']}
        position={[1.54, 0.26, 1.73]}
        rotation={[0, 0.77, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.fantasy_plant007.geometry}
        material={materials['Material.003']}
        position={[1.81, 0.3, 1.82]}
        rotation={[0, 0.57, 0]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.fantasy_plant008.geometry}
        material={materials['Material.003']}
        position={[1.81, 0.4, 1.49]}
        rotation={[0, 0.77, 0]}
        scale={0.14}
      />
      <mesh
        geometry={nodes.tree010.geometry}
        material={materials['Material.001']}
        position={[-1.52, 0.22, 0.08]}
        rotation={[0, -1.34, 0]}
        scale={0.25}
      />
      <mesh
        geometry={nodes.tree011.geometry}
        material={materials['Material.001']}
        position={[-1.52, 0.25, -0.21]}
        rotation={[Math.PI, -1.57, Math.PI]}
        scale={0.29}
      />
      <mesh
        geometry={nodes.tree012.geometry}
        material={materials['Material.001']}
        position={[1.65, 0.22, -1.14]}
        rotation={[-Math.PI, 1, -Math.PI]}
        scale={0.25}
      />
      <mesh
        geometry={nodes.tree013.geometry}
        material={materials['Material.001']}
        position={[1.65, 0.25, -0.92]}
        rotation={[-Math.PI, 1, -Math.PI]}
        scale={0.29}
      />
    </group>
  );
}

useGLTF.preload(glbs.t_flower_2_glb);
