/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 BirdHouse2.glb -t
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { glbs } from '@/public/assets/glb';

type GLTFResult = GLTF & {
  nodes: {
    실린더011: THREE.Mesh;
    실린더011_1: THREE.Mesh;
    실린더011_2: THREE.Mesh;
    실린더011_3: THREE.Mesh;
  };
  materials: {
    ['매테리얼.013']: THREE.MeshStandardMaterial;
    ['매테리얼.004']: THREE.MeshStandardMaterial;
    ['매테리얼.009']: THREE.MeshStandardMaterial;
    ['매테리얼.014']: THREE.MeshStandardMaterial;
  };
};

export function BirdHouse2(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(glbs.birdhouse_2_glb) as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.5}>
      <group
        position={[-0.02, 1.97, 0.73]}
        rotation={[-Math.PI / 2, -0.13, Math.PI]}
        scale={[0.05, 0.31, 0.05]}
      >
        <mesh
          geometry={nodes.실린더011.geometry}
          material={materials['매테리얼.013']}
          castShadow
        />
        <mesh
          geometry={nodes.실린더011_1.geometry}
          material={materials['매테리얼.004']}
          castShadow
        />
        <mesh
          geometry={nodes.실린더011_2.geometry}
          material={materials['매테리얼.009']}
          castShadow
        />
        <mesh
          geometry={nodes.실린더011_3.geometry}
          material={materials['매테리얼.014']}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbs.birdhouse_2_glb);
